# Modelado de Series Temporales de Aparcamientos usando RNNs y optimización con Optuna
En este notebook se abordará un problema de predicción de series temporales utilizando datos de disponibilidad de parkings.

Flujo de trabajo:
1. Agrupación de los datos por id de aparcamiento (idAparcamiento), para tratar cada parking como una serie temporal independiente.
2. División del conjunto de datos en tres subconjuntos: entrenamiento (train), validación (val) y prueba (test).
3. Entrenamiento de modelos de redes neuronales recurrentes simples (vanilla):
 - Vanilla RNN
 - Vanilla GRU
 - Vanilla LSTM
4. Ajuste de hiperparámetros utilizando Optuna para encontrar la configuración óptima en cada tipo de modelo.
5. Comparación de los resultados de rendimiento entre los distintos modelos utilizando métricas apropiadas.

El objetivo final es evaluar qué arquitectura ofrece mejores resultados para este tipo de datos y tarea de predicción.

## 0. Configuración global
Es altamente recomendable definir hiperparámetros como variables de entorno, en este caso vamos a usar variables globales para poder probar diferentes valores y ver su efecto.

In [1]:
import pandas as pd
import numpy as np
import json 
import os
import shutil

import torch
from torch import nn
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

import torch.optim as optim
from torch.optim.lr_scheduler import StepLR

import torchmetrics
from torchmetrics import MetricCollection
from torchmetrics.regression import MeanAbsoluteError, MeanSquaredError, MeanAbsolutePercentageError, R2Score

from tqdm import tqdm 
import time

import optuna
import optuna.visualization as vis

In [3]:
INPUT_COLS = ['PorcPlazasDisponibles', 'month', 'weekday', 'is_weekend']
TARGET_COL = 'PorcPlazasDisponibles'     

#Embedding sizes
MONTH_EMBEDDING_SIZE = 12  # 0-11
MONTH_EMBEDDING_PROJECTION_SIZE = 2  
WEEKDAY_EMBEDDING_SIZE = 7  # 0-6
WEEKDAY_EMBEDDING_PROJECTION_SIZE = 2 

DEVICE = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")
NUM_EPOCHS = 30
BATCH_SIZE = 32
HIDDEN_SIZE = 32
NUM_LAYERS = 1
DROPOUT_RATE = 0.2
LEARNING_RATE = 1e-3

OPTUNA_TRIALS = 2  # nº experimentos a probar con Optuna

INPUT_NUMERICAL_SIZE = 1
OUTPUT_SIZE = 1
WINDOW_INPUT_LENGTH = 24
WINDOW_OUTPUT_LENGTH = 1

## 1. Cargar los datos

In [4]:
df = pd.read_csv("../data/processed/data_processed.csv")

#convertir a indice
df.set_index("timestamp", inplace= True)
df.index = pd.to_datetime(df.index)
df["month"] = df.index.month - 1

In [47]:
df

,idAparcamiento,PlazasTotales,PlazasDisponibles,PorcPlazasDisponibles,year,month,day,weekday
timestamp,,,,,,,,
2023-02-03 10:00:00,6,372.0,60.0,16.129032,2023,1,3,4
2023-02-03 11:00:00,6,372.0,48.0,12.903226,2023,1,3,4
2023-02-03 12:00:00,6,372.0,66.0,17.741935,2023,1,3,4
2023-02-03 13:00:00,6,372.0,119.0,31.989247,2023,1,3,4
2023-02-03 14:00:00,6,372.0,155.0,41.666667,2023,1,3,4
...,...,...,...,...,...,...,...,...
2025-03-05 03:00:00,78,464.0,355.0,76.508621,2025,2,5,2
2025-03-05 04:00:00,78,464.0,355.0,76.508621,2025,2,5,2
2025-03-05 05:00:00,78,464.0,356.0,76.724138,2025,2,5,2
2025-03-05 06:00:00,78,464.0,354.0,76.293103,2025,2,5,2
2025-03-05 07:00:00,78,464.0,332.0,71.551724,2025,2,5,2

# 2. Ingeniería de características
- En problemas de series temporales, como la predicción de ocupación en servicios públicos, añadir variables temporales, como día de la semana o si es fin de semana, suelen aportar información valiosa para detectar patrones

In [5]:
df["is_weekend"] = df.weekday.apply(lambda x: 1 if x > 4 else 0)

- En lugar de usar el nº de plazas disponibles por parking, usamos el porcentaje de plazas disponibles en cada parking en un rango entre 0 y 1, para mejorar lo convergencia de las sigmoides de las RNN.

In [6]:
df['PorcPlazasDisponibles'] = df['PorcPlazasDisponibles'] / 100.0

In [7]:
df.drop(columns=["PlazasTotales", "PlazasDisponibles", "year", "day"], axis = 1, inplace=True)

In [7]:
df

,idAparcamiento,PorcPlazasDisponibles,month,weekday,is_weekend
timestamp,,,,,
2023-02-03 10:00:00,6,0.161290,1,4,0
2023-02-03 11:00:00,6,0.129032,1,4,0
2023-02-03 12:00:00,6,0.177419,1,4,0
2023-02-03 13:00:00,6,0.319892,1,4,0
2023-02-03 14:00:00,6,0.416667,1,4,0
...,...,...,...,...,...
2025-03-05 03:00:00,78,0.765086,2,2,0
2025-03-05 04:00:00,78,0.765086,2,2,0
2025-03-05 05:00:00,78,0.767241,2,2,0
2025-03-05 06:00:00,78,0.762931,2,2,0
2025-03-05 07:00:00,78,0.715517,2,2,0

## 2. División del conjunto de datos

Realizamos la división del conjunto de datos, agrupando por `idAparcamiento`. 
La idea es que el conjunto de **test sea común** para todos los aparcamientos, correspondiente al **último 10% del rango temporal total** del dataset. 

El resto de los datos disponibles para cada parking se dividen en:

- **Entrenamiento (train)**: el primer 85% de los datos previos al test.
- **Validación (val)**: el último 15% de los datos previos al test.

Con este split el rango temporal del conjunto de test es común a todos los aparcamientos. Mientras que el rango temporal del

In [8]:
from datetime import timedelta

# 1. Calcular el rango temporal global
fecha_min_global = df.index.min()
fecha_max_global = df.index.max()
rango_total = fecha_max_global - fecha_min_global

# 2. Calcular el inicio del conjunto de test (último 10% del rango)
test_ratio = 0.10
test_duration = timedelta(seconds=rango_total.total_seconds() * test_ratio)
test_start = fecha_max_global - test_duration

# 3. Diccionarios para almacenar los splits
train_dict = {}
val_dict = {}
test_dict = {}

val_ratio = 0.1  # del conjunto anterior al test

# 4. División por parking
for parking_id, group in df.groupby("idAparcamiento"):
    group = group.sort_index()
    
    # Split basado en el corte global
    test_set = group[group.index >= test_start]
    remaining = group[group.index < test_start]

    # Dividir en train y val
    val_size = int(len(remaining) * val_ratio)
    val_set = remaining.iloc[-val_size:]
    train_set = remaining.iloc[:-val_size]
    
    # Guardar resultados
    train_dict[parking_id] = train_set
    val_dict[parking_id] = val_set
    test_dict[parking_id] = test_set

In [9]:
train_dict

{6:                      idAparcamiento  PorcPlazasDisponibles  month  weekday  \
 timestamp
 2023-02-03 10:00:00               6               0.161290      1        4
 2023-02-03 11:00:00               6               0.129032      1        4
 2023-02-03 12:00:00               6               0.177419      1        4
 2023-02-03 13:00:00               6               0.319892      1        4
 2023-02-03 14:00:00               6               0.416667      1        4
 ...                             ...                    ...    ...      ...
 2024-09-05 17:00:00               6               0.509892      8        3
 2024-09-05 18:00:00               6               0.511505      8        3
 2024-09-05 19:00:00               6               0.524409      8        3
 2024-09-05 20:00:00               6               0.548602      8        3
 2024-09-05 21:00:00               6               0.588925      8        3

                      is_weekend
 timestamp
 2023-02-03 10:00:00           0
 2023-02-03 11:00:00           0
 2023-02-03 12:00:00           0
 2023-02-03 13:00:00           0
 2023-02-03 14:00:00           0
 ...                         ...
 2024-09-05 17:00:00           0
 2024-09-05 18:00:00           0
 2024-09-05 19:00:00           0
 2024-09-05 20:00:00           0
 2024-09-05 21:00:00           0

 [13932 rows x 5 columns],
 7:                      idAparcamiento  PorcPlazasDisponibles  month  weekday  \
 timestamp
 2023-02-03 10:00:00               7               0.288557      1        4
 2023-02-03 11:00:00               7               0.243781      1        4
 2023-02-03 12:00:00               7               0.243781      1        4
 2023-02-03 13:00:00               7               0.318408      1        4
 2023-02-03 14:00:00               7               0.343284      1        4
 ...                             ...                    ...    ...      ...
 2024-09-05 17:00:00               7               0.526965      8        3
 2024-09-05 18:00:00               7               0.553831      8        3
 2024-09-05 19:00:00               7               0.577711      8        3
 2024-09-05 20:00:00               7               0.592637      8        3
 2024-09-05 21:00:00               7               0.598607      8        3

                      is_weekend
 timestamp
 2023-02-03 10:00:00           0
 2023-02-03 11:00:00           0
 2023-02-03 12:00:00           0
 2023-02-03 13:00:00           0
 2023-02-03 14:00:00           0
 ...                         ...
 2024-09-05 17:00:00           0
 2024-09-05 18:00:00           0
 2024-09-05 19:00:00           0
 2024-09-05 20:00:00           0
 2024-09-05 21:00:00           0

 [13932 rows x 5 columns],
 8:                      idAparcamiento  PorcPlazasDisponibles  month  weekday  \
 timestamp
 2022-01-01 08:00:00               8               0.375000      0        5
 2022-01-01 09:00:00               8               0.390625      0        5
 2022-01-01 10:00:00               8               0.411458      0        5
 2022-01-01 11:00:00               8               0.416667      0        5
 2022-01-01 12:00:00               8               0.411458      0        5
 ...                             ...                    ...    ...      ...
 2024-07-27 22:00:00               8               0.668750      6        5
 2024-07-27 23:00:00               8               0.693750      6        5
 2024-07-28 00:00:00               8               0.709375      6        6
 2024-07-28 01:00:00               8               0.715625      6        6
 2024-07-28 02:00:00               8               0.715625      6        6

                      is_weekend
 timestamp
 2022-01-01 08:00:00           1
 2022-01-01 09:00:00           1
 2022-01-01 10:00:00           1
 2022-01-01 11:00:00           1
 2022-01-01 12:00:00           1
 ...                         ...
 2024-07-27 22:00:00           1
 2024-07-27 23:00:00           1
 2024-07-28 00:00:00           1
 2024-07-28 01:00:00           1
 2024-07-28 02:00:00           1

 [22531 rows x 5 columns],
 13:                      idAparcamiento  PorcPlazasDisponibles  month  weekday  \
 timestamp
 2023-02-03 10:00:00              13               0.148472      1        4
 2023-02-03 11:00:00              13               0.152838      1        4
 2023-02-03 12:00:00              13               0.205240      1        4
 2023-02-03 13:00:00              13               0.292576      1        4
 2023-02-03 14:00:00              13               0.353712      1        4
 ...                             ...                    ...    ...      ...
 2024-09-05 17:00:00              13               0.562969      8        3
 2024-09-05 18:00:00              13               0.560349      8        3
 2024-09-05 19:00:00              13               0.562969      8        3
 2024-09-05 20:00:00              13               0.560349      8        3
 2024-09-05 21:00:00              13               0.555109      8        3

                      is_weekend
 timestamp
 2023-02-03 10:00:00           0
 2023-02-03 11:00:00           0
 2023-02-03 12:00:00           0
 2023-02-03 13:00:00           0
 2023-02-03 14:00:00           0
 ...                         ...
 2024-09-05 17:00:00           0
 2024-09-05 18:00:00           0
 2024-09-05 19:00:00           0
 2024-09-05 20:00:00           0
 2024-09-05 21:00:00           0

 [13932 rows x 5 columns],
 34:                      idAparcamiento  PorcPlazasDisponibles  month  weekday  \
 timestamp
 2023-09-04 07:00:00              34               0.301370      8        0
 2023-09-04 08:00:00              34               0.223744      8        0
 2023-09-04 09:00:00              34               0.095890      8        0
 2023-09-04 10:00:00              34               0.068493      8        0
 2023-09-04 11:00:00              34               0.068493      8        0
 ...                             ...                    ...    ...      ...
 2024-09-27 00:00:00              34               0.479452      8        4
 2024-09-27 01:00:00              34               0.479452      8        4
 2024-09-27 02:00:00              34               0.479452      8        4
 2024-09-27 03:00:00              34               0.479452      8        4
 2024-09-27 04:00:00              34               0.474886      8        4

                      is_weekend
 timestamp
 2023-09-04 07:00:00           0
 2023-09-04 08:00:00           0
 2023-09-04 09:00:00           0
 2023-09-04 10:00:00           0
 2023-09-04 11:00:00           0
 ...                         ...
 2024-09-27 00:00:00           0
 2024-09-27 01:00:00           0
 2024-09-27 02:00:00           0
 2024-09-27 03:00:00           0
 2024-09-27 04:00:00           0

 [9334 rows x 5 columns],
 75:                      idAparcamiento  PorcPlazasDisponibles  month  weekday  \
 timestamp
 2022-01-01 10:00:00              75               0.462963      0        5
 2022-01-01 11:00:00              75               0.455556      0        5
 2022-01-01 12:00:00              75               0.429630      0        5
 2022-01-01 13:00:00              75               0.396296      0        5
 2022-01-01 14:00:00              75               0.388889      0        5
 ...                             ...                    ...    ...      ...
 2024-07-27 22:00:00              75               0.185185      6        5
 2024-07-27 23:00:00              75               0.351852      6        5
 2024-07-28 00:00:00              75               0.411111      6        6
 2024-07-28 01:00:00              75               0.411111      6        6
 2024-07-28 02:00:00              75               0.414815      6        6

                      is_weekend
 timestamp
 2022-01-01 10:00:00           1
 2022-01-01 11:00:00           1
 2022-01-01 12:00:00           1
 2022-01-01 13:00:00           1
 2022-01-01 14:00:00           1
 ...                         ...
 2024-07-27 22:00:00           1
 2024-07-27 23:00:00           1
 2024-07-28 00:00:00           1
 2024-07-28 01:00:00           1
 2024-07-28 02:00:00           1

 [22529 rows x 5 columns],
 77:                      idAparcamiento  PorcPlazasDisponibles  month  weekday  \
 timestamp
 2023-06-30 08:00:00              77               0.121387      5        4
 2023-06-30 09:00:00              77               0.069364      5        4
 2023-06-30 10:00:00              77               0.127168      5        4
 2023-06-30 11:00:00              77               0.173410      5        4
 2023-06-30 12:00:00              77               0.173410      5        4
 ...                             ...                    ...    ...      ...
 2024-09-20 10:00:00              77               0.017341      8        4
 2024-09-20 11:00:00              77               0.046243      8        4
 2024-09-20 12:00:00              77               0.080925      8        4
 2024-09-20 13:00:00              77               0.104046      8        4
 2024-09-20 14:00:00              77               0.202312      8        4

                      is_weekend
 timestamp
 2023-06-30 08:00:00           0
 2023-06-30 09:00:00           0
 2023-06-30 10:00:00           0
 2023-06-30 11:00:00           0
 2023-06-30 12:00:00           0
 ...                         ...
 2024-09-20 10:00:00           0
 2024-09-20 11:00:00           0
 2024-09-20 12:00:00           0
 2024-09-20 13:00:00           0
 2024-09-20 14:00:00           0

 [10759 rows x 5 columns],
 78:                      idAparcamiento  PorcPlazasDisponibles  month  weekday  \
 timestamp
 2023-11-29 06:00:00              78               0.732759     10        2
 2023-11-29 07:00:00              78               0.644397     10        2
 2023-11-29 08:00:00              78               0.405172     10        2
 2023-11-29 09:00:00              78               0.185345     10        2
 2023-11-29 10:00:00              78               0.107759     10        2
 ...                             ...                    ...    ...      ...
 2024-10-05 15:00:00              78               0.625000      9        5
 2024-10-05 16:00:00              78               0.564655      9        5
 2024-10-05 17:00:00              78               0.405172      9        5
 2024-10-05 18:00:00              78               0.355603      9        5
 2024-10-05 19:00:00              78               0.413793      9        5

                      is_weekend
 timestamp
 2023-11-29 06:00:00           0
 2023-11-29 07:00:00           0
 2023-11-29 08:00:00           0
 2023-11-29 09:00:00           0
 2023-11-29 10:00:00           0
 ...                         ...
 2024-10-05 15:00:00           1
 2024-10-05 16:00:00           1
 2024-10-05 17:00:00           1
 2024-10-05 18:00:00           1
 2024-10-05 19:00:00           1

 [7478 rows x 5 columns]}

In [54]:
train_dict[6]

,idAparcamiento,PorcPlazasDisponibles,month,weekday,is_weekend
timestamp,,,,,
2023-02-03 10:00:00,6,0.161290,1,4,0
2023-02-03 11:00:00,6,0.129032,1,4,0
2023-02-03 12:00:00,6,0.177419,1,4,0
2023-02-03 13:00:00,6,0.319892,1,4,0
2023-02-03 14:00:00,6,0.416667,1,4,0
...,...,...,...,...,...
2024-09-05 17:00:00,6,0.509892,8,3,0
2024-09-05 18:00:00,6,0.511505,8,3,0
2024-09-05 19:00:00,6,0.524409,8,3,0
2024-09-05 20:00:00,6,0.548602,8,3,0
2024-09-05 21:00:00,6,0.588925,8,3,0

## 3. Definir `Dataset` de pytorch

`TimeSeriesDataset` es una clase personalizada de `torch.utils.data.Dataset`, que permite definir datasets de Pytorch. En este caso facilita el manejo de secuencias en tareas de predicción en series temporales.

Actúa como un **pipeline** que:

- Genera automáticamente las ventanas de entrada (`input_window`) y salida (`output_window`) a partir de un DataFrame de series temporales.
- Convierte los datos en tensores (`torch.Tensor`) para que puedan ser procesados por modelos de PyTorch.

In [9]:
class TimeSeriesDataset(Dataset):
    def __init__(self, data, input_window, output_window, target_col):
        """
        numerical_data: DataFrame que contiene los datos numéricos de la serie temporal
        categorical_data: DataFrame que contiene los datos categóricos de la serie temporal
        input_window: nº de pasos de tiempo en la secuencia de entrada
        output_window: nº de pasos de tiempo a predecir
        feature_cols: lista de nombres de columnas que se usan como característcas
        target_col: nombre de la variable a predecir
        """
        self.data = data
        self.input_window = input_window
        self.output_window = output_window
        self.target_cols = target_col

    def __len__(self):
        """
        Función que devuele el nº de datos del Dataset
        """
        return len(self.data) - self.input_window - self.output_window + 1 #

    def __getitem__(self, idx):
        """
        Función que devuelve un dato a partir de un índice
        """
        X_endogena = self.data.iloc[idx: idx + self.input_window]["PorcPlazasDisponibles"].values
        X_month = self.data.iloc[idx + self.input_window]["month"].item()
        X_weekday = self.data.iloc[idx + self.input_window]["weekday"].item()
        X_is_weekend = self.data.iloc[idx + self.input_window]["is_weekend"].item()

        Y = self.data[idx + self.input_window: idx + self.input_window + self.output_window][self.target_cols].values
        
        X_endogena_tensor = torch.tensor(X_endogena, dtype= torch.float32)
        X_month_tensor = torch.tensor(X_month, dtype= torch.long)
        X_weekday_tensor = torch.tensor(X_weekday, dtype= torch.long)
        X_isweekend_tensor = torch.tensor(X_is_weekend, dtype= torch.long)
        Y_tensor = torch.tensor(Y, dtype= torch.float32)

        return X_endogena_tensor, X_month_tensor, X_weekday_tensor, X_isweekend_tensor, Y_tensor

In [10]:
prueba = TimeSeriesDataset(train_dict[6],
                  WINDOW_INPUT_LENGTH, 
                  WINDOW_OUTPUT_LENGTH, 
                  target_col=TARGET_COL)

In [11]:
prueba[0]

(tensor([0.1613, 0.1290, 0.1774, 0.3199, 0.4167, 0.4409, 0.4651, 0.4355, 0.4194,
         0.4731, 0.4704, 0.4946, 0.5645, 0.6613, 0.7151, 0.7231, 0.7258, 0.7285,
         0.7285, 0.7312, 0.7285, 0.7285, 0.6962, 0.6452]),
 tensor(1),
 tensor(5),
 tensor(1),
 tensor([0.5081]))

Dado que tenemos una serie temporal por parking, construimos un diccionario, donde las claves son los identificadores de parkings y los valores son Datasets de tipo `torch.utils.data.Dataset`.

In [12]:
train_datasets = {
    pid: TimeSeriesDataset(df, 
                           WINDOW_INPUT_LENGTH, 
                           WINDOW_OUTPUT_LENGTH, 
                           target_col=TARGET_COL)

    for pid, df in train_dict.items()
}

val_datasets = {
    pid: TimeSeriesDataset(df, 
                           WINDOW_INPUT_LENGTH, 
                           WINDOW_OUTPUT_LENGTH, 
                           target_col=TARGET_COL)
    for pid, df in val_dict.items()
}


test_datasets = {
    pid: TimeSeriesDataset(df, 
                           WINDOW_INPUT_LENGTH, 
                           WINDOW_OUTPUT_LENGTH, 
                           target_col=TARGET_COL)
                           
    for pid, df in test_dict.items()
}

Guardar `Datasets` de Pytorch

In [13]:
for pid, dataset in train_datasets.items():
    torch.save(dataset, f"../data/pytorch_datasets/train/parking_{pid}.pt")

In [14]:
for pid, dataset in test_datasets.items():
    torch.save(dataset, f"../data/pytorch_datasets/test/parking_{pid}.pt")

In [15]:
for pid, df in train_datasets.items():
    print("id parking: ", pid)
    print("longitud: ", len(df))

id parking:  6
longitud:  13908
id parking:  7
longitud:  13908
id parking:  8
longitud:  22507
id parking:  13
longitud:  13908
id parking:  34
longitud:  9310
id parking:  75
longitud:  22505
id parking:  77
longitud:  10735
id parking:  78
longitud:  7454

## 4. Crear `DataLoaders` a partir de `Dataset`

Para crear los `DataLoader`, seguimos el mismo criterio, es decir, crear un diccionario de DataLoaders, en el que cada iteración nos devuelve un batch de datos para cada parking.
- Cada batch de datos debe tener dimensión: `(batch_size, window_size, n_features)`

In [16]:
train_dataloaders = {
    pid: DataLoader(ts_dataset, batch_size = BATCH_SIZE, shuffle = True) #(batch_size, window_size, n_features)
    for pid, ts_dataset in train_datasets.items()
}

val_dataloaders = {
    pid: DataLoader(ts_dataset, batch_size = BATCH_SIZE, shuffle = True) #(batch_size, window_size, n_features)
    for pid, ts_dataset in val_datasets.items()
}

test_dataloaders = {
    pid: DataLoader(ts_dataset, batch_size = 2*BATCH_SIZE) #(batch_size, window_size, n_features)
    for pid, ts_dataset in test_datasets.items()
}

In [17]:
for pid, dloader in train_dataloaders.items():
    print("id parking", pid)
    for batch in dloader:
        print("Dimensión del primer batch de datos:", batch[0].shape)
        print("Dimensión del primer batch de etiquetas: ", batch[1].shape)


        break

    print("\n")

id parking 6
Dimensión del primer batch de datos: torch.Size([32, 24])
Dimensión del primer batch de etiquetas:  torch.Size([32])


id parking 7
Dimensión del primer batch de datos: torch.Size([32, 24])
Dimensión del primer batch de etiquetas:  torch.Size([32])


id parking 8
Dimensión del primer batch de datos: torch.Size([32, 24])
Dimensión del primer batch de etiquetas:  torch.Size([32])


id parking 13
Dimensión del primer batch de datos: torch.Size([32, 24])
Dimensión del primer batch de etiquetas:  torch.Size([32])


id parking 34
Dimensión del primer batch de datos: torch.Size([32, 24])
Dimensión del primer batch de etiquetas:  torch.Size([32])


id parking 75
Dimensión del primer batch de datos: torch.Size([32, 24])
Dimensión del primer batch de etiquetas:  torch.Size([32])


id parking 77
Dimensión del primer batch de datos: torch.Size([32, 24])
Dimensión del primer batch de etiquetas:  torch.Size([32])


id parking 78
Dimensión del primer batch de datos: torch.Size([32, 24])
Dimensión del primer batch de etiquetas:  torch.Size([32])

## 5. Definir Modelos (`RNN`,`GRU`,`LSTM`)

In [18]:
rnn = nn.RNN(input_size = INPUT_NUMERICAL_SIZE,
        hidden_size = HIDDEN_SIZE,
        num_layers = NUM_LAYERS,
        batch_first = True,
    ).to(DEVICE)

In [19]:
embedding_mes = nn.Embedding(MONTH_EMBEDDING_SIZE, MONTH_EMBEDDING_PROJECTION_SIZE).to(DEVICE)
embedding_weekday = nn.Embedding(WEEKDAY_EMBEDDING_SIZE, WEEKDAY_EMBEDDING_PROJECTION_SIZE).to(DEVICE)

In [20]:

#simular datos aleatorios con dimensiones adecuadas
x_endogena = torch.randn(BATCH_SIZE, WINDOW_INPUT_LENGTH, 1).to(DEVICE)  # (batch_size, sequence_length, num_features)
x_month = torch.randint(low = 0, high = MONTH_EMBEDDING_SIZE, size = (BATCH_SIZE, 1)).to(DEVICE)  # (batch_size, 1)
x_weekday = torch.randint(low = 0, high = WEEKDAY_EMBEDDING_SIZE, size = (BATCH_SIZE, 1)).to(DEVICE)  # (batch_size, 1)
x_is_weekend = torch.randint(low = 0, high = 2, size = (BATCH_SIZE, 1)).to(DEVICE)  # (batch_size, 1)


output_month = embedding_mes(x_month).squeeze(1)  # (batch_size, projection_size)
output_weekday = embedding_weekday(x_weekday).squeeze(1)  # (batch_size, projection_size)

all_hidden_states, last_hidden_state = rnn(x_endogena)
last_hidden_state = last_hidden_state.squeeze(0)  # (batch_size, hidden_size)

ej = torch.cat((last_hidden_state, output_month, output_weekday, x_is_weekend), dim=1)

In [98]:
last_hidden_state.shape

torch.Size([32, 32])

In [100]:
ej.shape

torch.Size([32, 37])

In [96]:
out_size = torch.nn.Linear(in_features = ej.shape[1], out_features = 1).to(DEVICE)
out_size(ej).shape

torch.Size([32, 1])

In [21]:
class VanillaRNN(nn.Module):
    def __init__(self,
                 input_size = INPUT_NUMERICAL_SIZE,
                 hidden_size = HIDDEN_SIZE,
                 output_size = OUTPUT_SIZE,
                 num_layers = NUM_LAYERS,
                 month_embedding_size = MONTH_EMBEDDING_SIZE,
                 month_embedding_projection_size = MONTH_EMBEDDING_PROJECTION_SIZE,
                 weekday_embedding_size = WEEKDAY_EMBEDDING_SIZE,
                 weekday_embedding_projection_size = WEEKDAY_EMBEDDING_PROJECTION_SIZE,
                 dropout = None):
        super().__init__()


        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.num_layers = num_layers
        self.dropout = 0.0 if dropout is None else dropout

        self.embedding_mes = nn.Embedding(month_embedding_size, month_embedding_projection_size)
        self.embedding_weekday = nn.Embedding(weekday_embedding_size, weekday_embedding_projection_size)

        #aplicar cuello de botella al nº de neuronas por capa en siguientes capas
        self.neurons_per_layer = [self.hidden_size // (2**i) for i in range(self.num_layers)]
        #CREAR BLOQUES: RNN + DROPOUT
        self.blocks = nn.ModuleList() #crear lista para almacenar bloques de pytorch (lstm + dropout)
        for i in range(num_layers):
            in_size = input_size if i == 0 else self.neurons_per_layer[i-1] #calcular de forma dinamica el tamaño de entrada a cada capa
            out_size = self.neurons_per_layer[i]
            self.blocks.append(nn.RNN(input_size= in_size,hidden_size=out_size, batch_first= True)) #añadir capa RNN

            #añadir dropout en todas las capas menos la última
            if i < num_layers-1:
                self.blocks.append(nn.Dropout(p = self.dropout))
        #capa final de salida
        self.fc = nn.Linear(in_features= self.neurons_per_layer[-1]+month_embedding_projection_size + weekday_embedding_projection_size + 1,  # +1 para el is_weekend
                            out_features = self.output_size)
        
    def forward(self, seq24, month, weekday, holiday):
        batch_size = seq24.size(0) #tamaño del batch
        out = seq24 #reasignar datos de entrada
        block_idx = 0

        for i in range(self.num_layers):
            rnn = self.blocks[block_idx]
            #inicializar celda de memoria y estado oculto aleatoriamente
            h0 = torch.zeros(1, batch_size, self.neurons_per_layer[i]).to(seq24.device)
            # out: all_hidde_states
            out, _ = rnn(out, h0)
            #actualizar indice para saltar dropout
            block_idx += 1
            # Aplicar dropout si corresponde
            if block_idx < len(self.blocks) and isinstance(self.blocks[block_idx], nn.Dropout):
                out = self.blocks[block_idx](out)
                block_idx += 1
        

        last_hidden_size = out[:, -1, :]  # Último paso temporal
        output_month = self.embedding_mes(month).squeeze(1)
        output_weekday = self.embedding_weekday(weekday).squeeze(1)

        print("last_hidden_size.shape:", last_hidden_size.shape)
        print("output_month.shape:", output_month.shape)
        print("output_weekday.shape:", output_weekday.shape)
        print("holiday.shape:", holiday.shape)

        final_output = torch.cat((last_hidden_size, output_month, output_weekday, holiday), dim=1)

        print("final_output.shape:", final_output.shape)

        return self.fc(final_output)

Comprobamos que no hay inconsistencias

In [22]:
model = VanillaRNN().to(DEVICE)
x_endogena = torch.randn(BATCH_SIZE, WINDOW_INPUT_LENGTH, INPUT_NUMERICAL_SIZE).to(DEVICE)  # (batch_size, sequence_length, num_features)
x_month = torch.randint(low = 0, high = MONTH_EMBEDDING_SIZE, size = (BATCH_SIZE, 1)).to(DEVICE)  # (batch_size, 1)
x_weekday = torch.randint(low = 0, high = WEEKDAY_EMBEDDING_SIZE, size = (BATCH_SIZE, 1)).to(DEVICE)  # (batch_size, 1)
x_is_weekend = torch.randint(low = 0, high = 2, size = (BATCH_SIZE, 1)).to(DEVICE)  # (batch_size, 1)
y  = model(x_endogena, x_month, x_weekday, x_is_weekend)
print(y.shape)  # → (32, 1)

last_hidden_size.shape: torch.Size([32, 32])
output_month.shape: torch.Size([32, 2])
output_weekday.shape: torch.Size([32, 2])
holiday.shape: torch.Size([32, 1])
final_output.shape: torch.Size([32, 37])
torch.Size([32, 1])

In [94]:
x_month.shape

torch.Size([32, 1])

In [23]:
# 3) Llamada a torch.onnx.export
import torch
torch.onnx.export(
    model,
    (x_endogena, x_month, x_weekday, x_is_weekend),  # tu tuple de entradas
    "parking_model.onnx",                            # fichero de salida
    export_params=True,      # guarda pesos dentro del ONNX
    opset_version=17,        # versión ONNX (>=11)
    do_constant_folding=True,
    input_names=[
      "past_24h_sequence",    # antes: "seq24"
      "month_of_year",        # antes: "month"
      "weekday_index",        # antes: "weekday"
      "is_weekend_flag"       # antes: "is_weekend"
    ],
    output_names=["predicted_occupancy"],  # antes: "yhat"
    dynamic_axes={
        "past_24h_sequence": {0: "batch_size", 1: "time_steps"},
        "month_of_year":     {0: "batch_size"},
        "weekday_index":     {0: "batch_size"},
        "is_weekend_flag":   {0: "batch_size"},
        "predicted_occupancy": {0: "batch_size"},
    }
)

last_hidden_size.shape: torch.Size([32, 32])
output_month.shape: torch.Size([32, 2])
output_weekday.shape: torch.Size([32, 2])
holiday.shape: torch.Size([32, 1])
final_output.shape: torch.Size([32, 37])

/home/frandovi/ts-parkings/TS-PARKINGS_VENV/lib64/python3.11/site-packages/torch/onnx/symbolic_opset9.py:4277: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with RNN_TANH can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model.
  warnings.warn(

In [24]:
class VanillaLSTM(nn.Module):
    def __init__(self,
                input_size = INPUT_NUMERICAL_SIZE, 
                hidden_size = HIDDEN_SIZE, 
                output_size = OUTPUT_SIZE, 
                num_layers = NUM_LAYERS, 
                month_embedding_size = MONTH_EMBEDDING_SIZE,
                month_embedding_projection_size = MONTH_EMBEDDING_PROJECTION_SIZE,
                weekday_embedding_size = WEEKDAY_EMBEDDING_SIZE,
                weekday_embedding_projection_size = WEEKDAY_EMBEDDING_PROJECTION_SIZE,
                dropout = None):
        super().__init__()

        
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.num_layers = num_layers
        self.dropout = 0.0 if dropout is None else dropout


        self.embedding_mes = nn.Embedding(month_embedding_size, month_embedding_projection_size)
        self.embedding_weekday = nn.Embedding(weekday_embedding_size, weekday_embedding_projection_size)


        #aplicar cuello de botella al nº de neuronas por capa en siguientes capas
        self.neurons_per_layer = [self.hidden_size // (2**i) for i in range(self.num_layers)]

        #CREAR BLOQUES: LSTM + DROPOUT
        self.blocks = nn.ModuleList() #crear lista para almacenar bloques de pytorch (lstm + dropout)

        for i in range(num_layers):
            in_size = input_size if i == 0 else self.neurons_per_layer[i-1] #calcular de forma dinamica el tamaño de entrada a cada capa
            out_size = self.neurons_per_layer[i]
            self.blocks.append(nn.LSTM(input_size= in_size,hidden_size=out_size, batch_first= True)) #añadir capa LSTM

            #añadir dropout en todas las capas menos la última
            if i < num_layers-1:
                self.blocks.append(nn.Dropout(p = self.dropout))

        #capa final de salida
        self.fc = nn.Linear(in_features= self.neurons_per_layer[-1]+month_embedding_projection_size + weekday_embedding_projection_size + 1,
                            out_features = self.output_size)
        
        
    def forward(self, seq24, month, weekday, holiday):
        batch_size = seq24.size(0) #tamaño del batch
        out = seq24 #reasignar datos de entrada
        block_idx = 0

        for i in range(self.num_layers):
            lstm = self.blocks[block_idx]

            #inicializar celda de memoria y estado oculto aleatoriamente
            h0 = torch.zeros(1, batch_size, self.neurons_per_layer[i]).to(seq24.device)
            c0 = torch.zeros(1, batch_size, self.neurons_per_layer[i]).to(seq24.device)

            # out: all_hidde_states
            out, _ = lstm(out, (h0, c0))

            #actualizar indice para saltar dropout
            block_idx += 1

            # Aplicar dropout si corresponde
            if block_idx < len(self.blocks) and isinstance(self.blocks[block_idx], nn.Dropout):
                out = self.blocks[block_idx](out)
                block_idx += 1

        last_hidden_size = out[:, -1, :]  # Último paso temporal
        output_month = self.embedding_mes(month).squeeze(1)
        output_weekday = self.embedding_weekday(weekday).squeeze(1)

        final_output = torch.cat((last_hidden_size, output_month, output_weekday, holiday), dim=1)

        return self.fc(final_output)

Comprobamos que no hay inconsistencias

In [25]:
model = VanillaLSTM().to(DEVICE)
x_endogena = torch.randn(BATCH_SIZE, WINDOW_INPUT_LENGTH, INPUT_NUMERICAL_SIZE).to(DEVICE)  # (batch_size, sequence_length, num_features)
x_month = torch.randint(low = 0, high = MONTH_EMBEDDING_SIZE, size = (BATCH_SIZE, 1)).to(DEVICE)  # (batch_size, 1)
x_weekday = torch.randint(low = 0, high = WEEKDAY_EMBEDDING_SIZE, size = (BATCH_SIZE, 1)).to(DEVICE)  # (batch_size, 1)
x_is_weekend = torch.randint(low = 0, high = 2, size = (BATCH_SIZE, 1)).to(DEVICE)  # (batch_size, 1)
y  = model(x_endogena, x_month, x_weekday, x_is_weekend)
print(y.shape)  # → (32, 1)

torch.Size([32, 1])

In [26]:
class VanillaGRU(nn.Module):
    def __init__(self,
                input_size = INPUT_NUMERICAL_SIZE, 
                hidden_size = HIDDEN_SIZE, 
                output_size = OUTPUT_SIZE, 
                num_layers = NUM_LAYERS,
                month_embedding_size = MONTH_EMBEDDING_SIZE,
                month_embedding_projection_size = MONTH_EMBEDDING_PROJECTION_SIZE,
                weekday_embedding_size = WEEKDAY_EMBEDDING_SIZE,
                weekday_embedding_projection_size = WEEKDAY_EMBEDDING_PROJECTION_SIZE,
                dropout = None):
        super().__init__()

        
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.num_layers = num_layers
        self.dropout = 0.0 if dropout is None else dropout

        self.embedding_mes = nn.Embedding(month_embedding_size, month_embedding_projection_size)
        self.embedding_weekday = nn.Embedding(weekday_embedding_size, weekday_embedding_projection_size)


        #aplicar cuello de botella al nº de neuronas por capa en siguientes capas
        self.neurons_per_layer = [self.hidden_size // (2**i) for i in range(self.num_layers)]

        #CREAR BLOQUES: GRU + DROPOUT
        self.blocks = nn.ModuleList() #crear lista para almacenar bloques de pytorch (lstm + dropout)

        for i in range(num_layers):
            in_size = input_size if i == 0 else self.neurons_per_layer[i-1] #calcular de forma dinamica el tamaño de entrada a cada capa
            out_size = self.neurons_per_layer[i]
            self.blocks.append(nn.GRU(input_size= in_size,hidden_size=out_size, batch_first= True)) #añadir capa GRU

            #añadir dropout en todas las capas menos la última
            if i < num_layers-1:
                self.blocks.append(nn.Dropout(p = self.dropout))

        #capa final de salida
        self.fc = nn.Linear(in_features= self.neurons_per_layer[-1]+month_embedding_projection_size + weekday_embedding_projection_size + 1,
                            out_features = self.output_size)
        
        
    def forward(self, seq24, month, weekday, holiday):
        batch_size = seq24.size(0) #tamaño del batch
        out = seq24 #reasignar datos de entrada
        block_idx = 0

        for i in range(self.num_layers):
            gru = self.blocks[block_idx]

            #inicializar celda de memoria y estado oculto aleatoriamente
            h0 = torch.zeros(1, batch_size, self.neurons_per_layer[i]).to(seq24.device)
            
            # out: all_hidde_states
            out, _ = gru(out, h0)

            #actualizar indice para saltar dropout
            block_idx += 1

            # Aplicar dropout si corresponde
            if block_idx < len(self.blocks) and isinstance(self.blocks[block_idx], nn.Dropout):
                out = self.blocks[block_idx](out)
                block_idx += 1

        last_hidden_size = out[:, -1, :]  # Último paso temporal
        output_month = self.embedding_mes(month).squeeze(1)
        output_weekday = self.embedding_weekday(weekday).squeeze(1)

        final_output = torch.cat((last_hidden_size, output_month, output_weekday, holiday), dim=1)

        return self.fc(final_output)

In [27]:
model = VanillaGRU().to(DEVICE)
x_endogena = torch.randn(BATCH_SIZE, WINDOW_INPUT_LENGTH, INPUT_NUMERICAL_SIZE).to(DEVICE)  # (batch_size, sequence_length, num_features)
x_month = torch.randint(low = 0, high = MONTH_EMBEDDING_SIZE, size = (BATCH_SIZE, 1)).to(DEVICE)  # (batch_size, 1)
x_weekday = torch.randint(low = 0, high = WEEKDAY_EMBEDDING_SIZE, size = (BATCH_SIZE, 1)).to(DEVICE)  # (batch_size, 1)
x_is_weekend = torch.randint(low = 0, high = 2, size = (BATCH_SIZE, 1)).to(DEVICE)  # (batch_size, 1)
y  = model(x_endogena, x_month, x_weekday, x_is_weekend)
print(y.shape)  # → (32, 1)

torch.Size([32, 1])

## 6. Definir métricas

In [28]:
metrics = MetricCollection({
    "MAE": MeanAbsoluteError(),
    "MSE": MeanSquaredError(),
    "RMSE": MeanSquaredError(squared = False)
})

## 7. Instanciar modelos, optimizador, función de coste y learning rate scheduler

#### 💡 Estructura de entrenamiento modular por parking y arquitectura

Dado que tenemos:

- Un diccionario de datasets por `idAparcamiento`
- Tres arquitecturas distintas: `RNN`, `LSTM`, y `GRU`

Cada modelo se entrena **por separado para cada parking**, permitiendo una evaluación más precisa por serie temporal individual.

Para hacerlo **flexible y escalable**, organizamos todos los componentes en **diccionarios anidados**. Cada uno almacena los elementos necesarios para entrenar y validar por `idAparcamiento` y por tipo de modelo:

- `models["rnn"][pid]`, `models["lstm"][pid]`, etc.
- `optimizers["gru"][pid]`, `criterions["lstm"][pid]`, etc.
- `schedulers["rnn"][pid]` para aplicar estrategias de LR por modelo

Esto nos permite:

- Entrenar múltiples arquitecturas de forma aislada y comparable  
- Hacer tuning o validación cruzada por parking  
- Comparar vanilla vs. modelos optimizados con Optuna  
- Guardar y cargar modelos individuales por ID

Esta estructura es especialmente útil en contextos donde las series tienen longitudes o comportamientos distintos, como ocurre con los parkings reales.

1. Definir estructuras adecuadas: diccionarios de diccionarios

In [29]:
models = {
    "rnn": {},
    "lstm": {},
    "gru": {}
}

criterions = {
    "rnn": {},
    "lstm": {},
    "gru": {}
}

optimizers = {
    "rnn": {},
    "lstm": {},
    "gru": {}
}

schedulers = {
    "rnn": {},
    "lstm": {},
    "gru": {}
}

model_classes = {
    "lstm": VanillaLSTM,
    "gru": VanillaGRU,
    "rnn": VanillaRNN
}

2. Definir una función para inicializar los componentes

In [30]:
def init_model_components(model_class, 
                          input_size, 
                          hidden_size, 
                          output_size, 
                          month_embedding_size,
                          month_embedding_projection_size,
                          weekday_embedding_size,
                          weekday_embedding_projection_size, 
                          dropout,
                          device, 
                          num_layers = NUM_LAYERS, 
                          lr = LEARNING_RATE):
    """
    Función para instanciar los componentes: modelo, función de pérdida, optimizer, learning rate scheduler
    """
    model = model_class(input_size, 
                        hidden_size, 
                        output_size, 
                        num_layers, 
                        month_embedding_size,
                        month_embedding_projection_size,
                        weekday_embedding_size,
                        weekday_embedding_projection_size, 
                        dropout
                        ).to(device)
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr = lr)

    scheduler = StepLR(
    optimizer,     # optimizador
    step_size=10,  # reduce cada 10 epochs
    gamma=0.05     # (lr = lr * gamma)
)

    return model, criterion, optimizer, scheduler

3. Construir modelos, criterions, optimizers y schedulers por parking

In [31]:
INPUT_NUMERICAL_SIZE

1

In [32]:
for pid, dataset in train_datasets.items():
    #RNN
    model, criterion, optimizer, scheduler = init_model_components(model_class = VanillaRNN, 
                                                                   input_size = INPUT_NUMERICAL_SIZE, 
                                                                   hidden_size = HIDDEN_SIZE,
                                                                   output_size = OUTPUT_SIZE,
                                                                   num_layers = NUM_LAYERS,
                                                                   month_embedding_size = MONTH_EMBEDDING_SIZE,
                                                                   month_embedding_projection_size = MONTH_EMBEDDING_PROJECTION_SIZE,
                                                                   weekday_embedding_size = WEEKDAY_EMBEDDING_SIZE,
                                                                   weekday_embedding_projection_size = WEEKDAY_EMBEDDING_PROJECTION_SIZE, 
                                                                   dropout = DROPOUT_RATE,
                                                                   device = DEVICE,
                                                                   lr= LEARNING_RATE)
    models["rnn"][pid] = model
    criterions["rnn"][pid] = criterion
    optimizers["rnn"][pid] = optimizer
    schedulers["rnn"][pid] = scheduler

    #LSTM
    model, criterion, optimizer, scheduler = init_model_components(model_class = VanillaLSTM,
                                                                   input_size= INPUT_NUMERICAL_SIZE,
                                                                   hidden_size = HIDDEN_SIZE,
                                                                   output_size = OUTPUT_SIZE,
                                                                   num_layers = NUM_LAYERS,
                                                                   month_embedding_size = MONTH_EMBEDDING_SIZE,
                                                                   month_embedding_projection_size = MONTH_EMBEDDING_PROJECTION_SIZE,
                                                                   weekday_embedding_size = WEEKDAY_EMBEDDING_SIZE,
                                                                   weekday_embedding_projection_size = WEEKDAY_EMBEDDING_PROJECTION_SIZE, 
                                                                   dropout = DROPOUT_RATE,
                                                                   device = DEVICE,
                                                                   lr= LEARNING_RATE)
    models["lstm"][pid] = model
    criterions["lstm"][pid] = criterion
    optimizers["lstm"][pid] = optimizer
    schedulers["lstm"][pid] = scheduler

    #GRU
    model, criterion, optimizer, scheduler = init_model_components(model_class = VanillaGRU,
                                                                   input_size= INPUT_NUMERICAL_SIZE,
                                                                   hidden_size = HIDDEN_SIZE,
                                                                   output_size = OUTPUT_SIZE,
                                                                   num_layers = NUM_LAYERS,
                                                                   month_embedding_size = MONTH_EMBEDDING_SIZE,
                                                                   month_embedding_projection_size = MONTH_EMBEDDING_PROJECTION_SIZE,
                                                                   weekday_embedding_size = WEEKDAY_EMBEDDING_SIZE,
                                                                   weekday_embedding_projection_size = WEEKDAY_EMBEDDING_PROJECTION_SIZE, 
                                                                   dropout = DROPOUT_RATE,
                                                                   device = DEVICE,
                                                                   lr= LEARNING_RATE)
    models["gru"][pid] = model
    criterions["gru"][pid] = criterion
    optimizers["gru"][pid] = optimizer
    schedulers["gru"][pid] = scheduler

## 8. Crear callbacks

In [33]:
class EarlyStoppingCallback:
    def __init__(self, patience=5, delta=0.0, verbose=False, path='checkpoint.pt'):
        self.patience = patience
        self.delta = delta
        self.verbose = verbose
        self.path = path

        self.counter = 0
        self.best_loss = None
        self.early_stop = False

    def __call__(self, val_loss, model):
        if self.best_loss is None:
            self.best_loss = val_loss
            self.save_checkpoint(val_loss, model)
        elif val_loss < self.best_loss - self.delta:
            # 🔁 Mejora
            self.best_loss = val_loss
            self.save_checkpoint(val_loss, model)
            self.counter = 0
        else:
            self.counter += 1
            if self.verbose:
                print(f"🛑 EarlyStopping: {self.counter}/{self.patience} sin mejora")
            if self.counter >= self.patience:
                self.early_stop = True

        return self.early_stop

    def save_checkpoint(self, val_loss, model):
        if self.verbose:
            print(f"✅ Mejor val_loss: {val_loss:.6f}. Guardando modelo...")
        torch.save(model.state_dict(), self.path)

## 9. Definir función de validación

In [34]:
from tqdm import tqdm
import time

def validate_one_epoch(
    model,
    dataloader,
    criterion,
    metrics, 
    device,
    epoch=None
):
    """
    Ejecuta una pasada de validación completa (1 epoch) sobre un dataloader.

    Args:
        model (nn.Module): Modelo PyTorch a evaluar.
        dataloader (DataLoader): Dataloader con los datos de validación.
        criterion (nn.Module): Función de pérdida (loss).
        metrics (torchmetrics.MetricCollection): Métricas a evaluar.
        device (str): "cpu" o "cuda".
        epoch (int, optional): Número de epoch actual (solo para mostrar).

    Returns:
        dict: Diccionario con loss promedio y métricas calculadas.
    """

    model.eval()  # poner modelo en modo evaluación

    running_loss = 0.0
    num_batches = len(dataloader)

    metrics.to(device)
    metrics.reset()

    start_time = time.time()

    # tqdm para barra de progreso
    progress_bar = tqdm(dataloader, desc=f"Epoch {epoch} [Val]", leave=False)

    with torch.no_grad():
        for x_endogena_batch, x_month_batch, x_weekday_batch, x_is_weekend_batch, y_batch in progress_bar:
            x_endogena_batch = x_endogena_batch.unsqueeze(2).to(device)
            x_month_batch = x_month_batch.unsqueeze(1).to(device)
            x_weekday_batch = x_weekday_batch.unsqueeze(1).to(device)
            x_is_weekend_batch = x_is_weekend_batch.unsqueeze(1).to(device)
            y_batch = y_batch.to(device)

            # Forward
            y_pred = model(x_endogena_batch, 
                           x_month_batch, 
                           x_weekday_batch, 
                           x_is_weekend_batch)

            # Calcular loss y acumularlo
            loss = criterion(y_pred, y_batch)
            running_loss += loss.item()

            # Actualizar métricas
            metrics.update(y_pred, y_batch)

            # Mostrar loss promedio hasta el batch actual
            batch_idx = progress_bar.n
            avg_loss_so_far = running_loss / (batch_idx + 1)
            progress_bar.set_postfix({"Loss": avg_loss_so_far})

    #calcular loss promedio del batch
    avg_loss = running_loss / num_batches

    #calcular metrica total: promedio de metricas de cada batch
    metric_results = metrics.compute()

    #crear diccionario de resutaldos: primer elemento del diccionario es el loss
    results = {"val_loss": avg_loss}
    #añadir elementos al diccionario: cada par clave-valor es una métrica
    results.update({k: v.item() for k, v in metric_results.items()})


    return results

Probamos que no hay inconsistencias, a pesar de que los pesos de los modelos sean aleatorios

In [35]:
val_results = validate_one_epoch(
    model=models["lstm"][6],
    dataloader=val_dataloaders[6],
    criterion=criterions["lstm"][6],
    metrics = metrics,
    device= DEVICE,
    epoch=1
)

print(val_results)

{'val_loss': 0.24135736655443907, 'MAE': 0.43564286828041077, 'MSE': 0.24125497043132782, 'RMSE': 0.49117714166641235}

## 10. Definir bucle de entrenamiento

In [36]:
def train_one_epoch(
                model,
                dataloader,
                criterion,
                optimizer,
                metrics,
                device,
                epoch = None
):
        """
        Ejecuta una epoch completa de entrenamiento.

        Args:
                model (nn.Module): Modelo a entrenar.
                dataloader (DataLoader): Dataloader con datos de entrenamiento.
                criterion (nn.Module): Función de pérdida.
                optimizer (Optimizer): Optimizador para actualizar pesos.
                metrics (torchmetrics.MetricCollection): Métricas de evaluación.
                device (str): "cpu" o "cuda".
                epoch (int, optional): Número de la época actual (solo para mostrar).

        Returns:
                dict: Diccionario con loss promedio y métricas acumuladas.
        """
        
        model.train() #poner modelo en modo entrenamiento

        #inicializar loss y nº de batches
        running_loss = 0.0
        num_batches = len(dataloader)

        #inicializar métricas y moverlas al device
        metrics.to(device)
        metrics.reset()

        #coger tiempo actual de referencia
        start_time = time.time()

        #inicializar barra de progreso
        #progress_bar envuelve el dataloader y lo monitoriza
        progress_bar = tqdm(dataloader, desc=f"Epoch {epoch}", leave=False)

        for x_endogena_batch, x_month_batch, x_weekday_batch, x_is_weekend_batch, y_batch in progress_bar:
              x_endogena_batch = x_endogena_batch.unsqueeze(2).to(device)
              x_month_batch = x_month_batch.unsqueeze(1).to(device)
              x_weekday_batch = x_weekday_batch.unsqueeze(1).to(device)
              x_is_weekend_batch = x_is_weekend_batch.unsqueeze(1).to(device)
              y_batch = y_batch.to(device)
              
              optimizer.zero_grad() #1. resetear gradientes
        
              y_pred = model(x_endogena_batch, #2. Forward
                              x_month_batch, 
                              x_weekday_batch, 
                              x_is_weekend_batch)          
              
              loss = criterion(y_pred, y_batch) # 3. calcular loss
              running_loss += loss.item()
              
              batch_idx = progress_bar.n #indice del batch
              avg_loss_so_far = running_loss / (batch_idx + 1)             
              #Mostrar en tiempo real el loss
              progress_bar.set_postfix({"Loss": avg_loss_so_far})          
              loss.backward() #4. Propagar loss
              optimizer.step() #5. Actualizar pesos        
              metrics.update(y_pred, y_batch) #6. Actualizar métricas 
        
        #calcular loss promedio del batch
        avg_loss = running_loss/num_batches

        #calcular metrica total: promedio de metricas de cada batch
        metric_results = metrics.compute()

        #crear diccionario de resutaldos: primer elemento del diccionario es el loss
        results = {"train_loss": avg_loss}

        #añadir elementos al diccionario: cada par clave-valor es una métrica
        results.update({k: v.item() for k,v in metric_results.items()})

        return results

Probamos que no hay inconsistencias, a pesar de que los pesos de los modelos sean aleatorios

In [37]:
train_results = train_one_epoch(
    model=models["lstm"][6],
    dataloader=train_dataloaders[6],
    criterion=criterions["lstm"][6],
    optimizer=optimizers["lstm"][6],
    metrics=metrics,
    device=DEVICE,
    epoch = 1
)

print(train_results)

{'train_loss': 0.02868607173855791, 'MAE': 0.12281154096126556, 'MSE': 0.028700033202767372, 'RMSE': 0.169410839676857}

## 11. Entrenamiento

In [38]:
def fit_simple(
    model,
    train_loader,
    val_loader,
    criterion,
    optimizer,
    metrics,
    scheduler=None,
    num_epochs=10,
    device="cpu",
    early_stopper = None,

):
    """
    Entrena un modelo simple (debug/test) para un solo parking. 
    Devuelve el modelo entrenado, el historial y las métricas finales.
    Incluye prints detallados por época.
    """
    history = []
    model.to(device)

    for epoch in range(1, num_epochs + 1):
        epoch_start = time.time()

        train_metrics = train_one_epoch(
            model=model,
            dataloader=train_loader,
            criterion=criterion,
            optimizer=optimizer,
            metrics=metrics.clone(),
            device=device,
            epoch=epoch
        )

        val_metrics = validate_one_epoch(
            model=model,
            dataloader=val_loader,
            criterion=criterion,
            metrics=metrics.clone(),
            device=device,
            epoch=epoch,
        )

        if scheduler:
            scheduler.step()

        combined = {"epoch": epoch}
        combined.update(train_metrics)
        combined.update(val_metrics)
        history.append(combined)

         # Tiempo total de la época
        total_time = time.time() - epoch_start

        # mostrar logs con emojis para mayor claridad
        print(
            f"📊 Epoch {epoch}/{num_epochs} | "
            f"Train Loss: {train_metrics['train_loss']:.4f} | "
            f"Train MAE: {train_metrics.get('MAE', 0):.2f} | "
            f"Val Loss: {val_metrics['val_loss']:.4f} | "
            f"Val MAE: {val_metrics.get('MAE', 0):.2f} | "
            f"⏱️ Time: {total_time:.1f}s"
        )

        # Early stopping
        if early_stopper is not None:
            if early_stopper(val_metrics["val_loss"], model):
                print(f"⛔ Parada temprana en epoch {epoch} por falta de mejora.")
                break

    return model, history, val_metrics

In [39]:
model_trained, history, final_metrics = fit_simple(
    model=models["lstm"][6],
    train_loader=train_dataloaders[6],
    val_loader=val_dataloaders[6],
    criterion=criterions["lstm"][6],
    optimizer=optimizers["lstm"][6],
    scheduler=schedulers["lstm"][6],
    metrics=metrics,  # una instancia de MetricCollection
    num_epochs=2,
    device=DEVICE,
    early_stopper= None
)

📊 Epoch 1/2 | Train Loss: 0.0074 | Train MAE: 0.06 | Val Loss: 0.0058 | Val MAE: 0.06 | ⏱️ Time: 5.6s

📊 Epoch 2/2 | Train Loss: 0.0040 | Train MAE: 0.05 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 5.8s

## 13. Exportación de checkpoints, logs y resultados

In [34]:
def get_experiment_path(base_dir="../experiments", parking_id=None, modelo=None, tipo=None):
    """
    Construye la ruta donde se guardarán los resultados del experimento.

    Args:
        base_dir (str): Carpeta base donde se guardan los experimentos.
        parking_id (int or str): ID del parking.
        modelo (str): Nombre del modelo ("lstm", "gru", "rnn").
        tipo (str): "vanilla" o "optuna".

    Returns:
        str: Ruta completa del experimento.
        EJEMPLO: ../experiments/6/lstm/optuna
    """
    assert parking_id is not None and modelo is not None and tipo is not None, "Faltan argumentos para definir la ruta"

    # Estandarizar nombres
    parking_folder = f"parking_{parking_id}"
    modelo = modelo.lower()
    tipo = tipo.lower()

    return os.path.join(base_dir, parking_folder, modelo, tipo)

In [35]:
def save_experiment_results(
    base_dir,
    model,
    history,
    final_metrics,
    save_model=True
):
    """
    Guarda los resultados del experimento: modelo, historial y métricas finales en su carpeta correspondiente

    Args:
        base_dir (str): Ruta donde guardar los archivos.
        model (nn.Module): Modelo entrenado.
        history (list): Lista de dicts con métricas por época.
        final_metrics (dict): Métricas finales de validación.
        save_model (bool): Si guardar o no el modelo (.pt).
    """
    os.makedirs(base_dir, exist_ok=True)

    # Guardar modelo
    if save_model:
        model_path = os.path.join(base_dir, "best_model.pt")
        torch.save(model.state_dict(), model_path)

    # Guardar historial
    history_path = os.path.join(base_dir, "history.json")
    with open(history_path, "w") as f:
        json.dump(history, f, indent=2)

    # Guardar métricas finales
    metrics_path = os.path.join(base_dir, "metrics.json")
    with open(metrics_path, "w") as f:
        json.dump(final_metrics, f, indent=2)

In [36]:
def log_experiment_summary(
    csv_path,
    parking_id,
    modelo,
    tipo,
    final_metrics,
    best_params=None
):
    """
    Añade un experimento al archivo CSV resumen global.

    Args:
        csv_path (str): Ruta del archivo CSV de resumen.
        parking_id (int): ID del parking.
        modelo (str): Nombre del modelo ("rnn", "lstm", "gru", etc.).
        tipo (str): "vanilla" o "optuna".
        final_metrics (dict): Métricas finales del experimento.
        best_params (dict, optional): Parámetros optimizados (si aplica).
    """

    # Cargar el CSV si existe, sino crear uno nuevo
    if os.path.exists(csv_path):
        df = pd.read_csv(csv_path)
    else:
        df = pd.DataFrame()

    # Crear fila con info del experimento
    row = {
        "parking_id": parking_id,
        "modelo": modelo,
        "tipo": tipo,
    }

    # Agregar métricas finales
    row.update(final_metrics)

    # Agregar hiperparámetros si hay
    if best_params:
        for k, v in best_params.items():
            row[f"param_{k}"] = v

    # Agregar al DataFrame
    df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)

    # Guardar de nuevo
    df.to_csv(csv_path, index=False)

In [3]:
5e-3

0.005

## 14. Optimización de hiperparámetros con `Optuna`

In [37]:
def get_objective(model_class, pid, arch_name, input_size, output_size, dropout, train_loader, val_loader, device, metrics, num_epochs=10):
    """
    Devuelve una función objective(trial) para Optuna, adaptada al modelo y parking.
    """

    def objective(trial):
        # Espacio de búsqueda
        hidden_size = trial.suggest_categorical("hidden_size", [16, 32, 64])
        num_layers = trial.suggest_int("num_layers", 2, 4, step = 1)
        lr = trial.suggest_float("lr", 5e-3, 1e-2, log=True)

        # Mostrar los hiperparámetros probados
        print(f"\n🔁 Trial {trial.number}")
        print(f"   🔧 Params → hidden_size: {hidden_size}, num_layers: {num_layers}, lr: {lr:.5f}")
        print("────────────────────────────────────────────────────────────")

        # Rutas
        base_dir = get_experiment_path("experimentos", pid, arch_name, "optuna") #ruta donde guardar el experimento 
        os.makedirs(base_dir, exist_ok=True)
        checkpoint_path = os.path.join(base_dir, f"trial_{trial.number}_best_model.pt") #crear ruta donde se guardarán pesos del modelo


        #construir callback en cada trial ya que si no lo hacemos no se reinicia el contador de épocas sin mejora
        EARLY_STOPPER = EarlyStoppingCallback(
            patience=5,
            delta=0.00001,
            verbose=True,
            path=checkpoint_path
        )

        # Inicializar modelo y componentes
        model, criterion, optimizer, scheduler = init_model_components(
            model_class,
            input_size=input_size,
            hidden_size=hidden_size,
            output_size=output_size,
            dropout = dropout,
            num_layers=num_layers,
            device=device,
            lr=lr
        )

        # Entrenar
        _, _, val_metrics = fit_simple(
            model=model,
            train_loader=train_loader,
            val_loader=val_loader,
            criterion=criterion,
            optimizer=optimizer,
            metrics=metrics,
            scheduler=None,
            num_epochs=num_epochs,
            device=device,
            early_stopper = EARLY_STOPPER
        )
        print(f"🎯 Resultado trial {trial.number} → val_loss = {val_metrics['val_loss']:.4f}")
       
        # Guardar métricas dentro del trial
        trial.set_user_attr("final_metrics", val_metrics)
        trial.set_user_attr("checkpoint_path", checkpoint_path)

        return val_metrics["val_loss"]

    return objective

## 15. Entrenamiento final

In [38]:
for arch_name in ["rnn", "lstm", "gru"]:
    for pid in train_dataloaders.keys():
        print(f"\n\n📍 Parking {pid} | 🧠 Modelo: {arch_name.upper()}\n{'─'*30}")



        model_class = model_classes[arch_name]  # dict con clases: {"lstm": VanillaLSTM, ...}
        
        ## 1. Entrenamiento VANILLA
        print("🛠️ Entrenamiento versión VANILLA")

        #crear rutas
        base_dir_vanilla = get_experiment_path("../experiments/validation", pid, arch_name, "vanilla") #ruta donde se guardan datos del experimento
        os.makedirs(base_dir_vanilla, exist_ok=True) #crearla si no existe
        checkpoint_path_vanilla = os.path.join(base_dir_vanilla, "best_model.pt") #crear ruta
        EARLY_STOPPER = EarlyStoppingCallback(patience=5,delta=0.001,verbose=True,path=checkpoint_path_vanilla)

        
        model_vanilla, history_v, final_metrics_v = fit_simple(
            model=models[arch_name][pid],
            train_loader=train_dataloaders[pid],
            val_loader=val_dataloaders[pid],
            criterion=criterions[arch_name][pid],
            optimizer=optimizers[arch_name][pid],
            metrics=metrics,
            scheduler=schedulers[arch_name][pid],
            num_epochs=NUM_EPOCHS,
            device=DEVICE,
            early_stopper= EARLY_STOPPER
        )

        #guardar resultados
        save_experiment_results(base_dir_vanilla, model_vanilla, history_v, final_metrics_v)
        log_experiment_summary("../experiments/validation/experiments_summary.csv", pid, arch_name, "vanilla", final_metrics_v)

        ## 2. Optuna
        print(f"\n🧪 Optimizando {arch_name.upper()} con Optuna para parking {pid}...\n")

        objective_fn = get_objective(
            model_class=model_class,
            pid=pid,
            arch_name= arch_name,
            input_size=INPUT_SIZE,
            output_size=OUTPUT_SIZE,
            dropout= DROPOUT_RATE,
            train_loader=train_dataloaders[pid],
            val_loader=val_dataloaders[pid],
            device=DEVICE,
            metrics=metrics,
            num_epochs=NUM_EPOCHS,
        )

        #quitar logs no deseados
        optuna.logging.set_verbosity(optuna.logging.WARNING)

        #crear estudio con optuna
        study = optuna.create_study(direction="minimize")
        study.optimize(objective_fn, n_trials=OPTUNA_TRIALS)

        best_trial = study.best_trial
        best_params = best_trial.params
        best_metrics = best_trial.user_attrs.get("final_metrics", {})
        best_model_src = best_trial.user_attrs.get("checkpoint_path")

        #Mostrar mejores hiperparámetros encontrados
        print("\n🥇 Mejores hiperparámetros encontrados:")
        for k, v in best_params.items():
            print(f"   - {k}: {v}")

        # Ruta para guardar el modelo final
        base_dir_optuna = get_experiment_path("../experiments/validation", pid, arch_name, "optuna")
        os.makedirs(base_dir_optuna, exist_ok=True)

        # Copiar modelo del mejor trial
        best_model_dst = os.path.join(base_dir_optuna, "best_model.pt")
        shutil.copy(best_model_src, best_model_dst)


        with open(os.path.join(base_dir_optuna, "best_params.json"), "w") as f:
            json.dump(best_params, f, indent=2)

        log_experiment_summary(
            csv_path="../experiments/validation/experiments_summary.csv",
            parking_id=pid,
            modelo=arch_name,
            tipo="optuna",
            final_metrics=best_metrics,
            best_params=best_params
        )
    print("\n\n")
print("\n\n\n")

📍 Parking 6 | 🧠 Modelo: RNN
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0190 | Train MAE: 0.10 | Val Loss: 0.0076 | Val MAE: 0.06 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.007632. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0050 | Train MAE: 0.05 | Val Loss: 0.0043 | Val MAE: 0.05 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.004252. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.003122. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.

🧪 Optimizando RNN con Optuna para parking 6...


🔁 Trial 0
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00796
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0118 | Train MAE: 0.07 | Val Loss: 0.0035 | Val MAE: 0.04 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.003539. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.002365. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002270. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.002111. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0024

🔁 Trial 1
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00907
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0466 | Train MAE: 0.17 | Val Loss: 0.0165 | Val MAE: 0.10 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.016543. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0072 | Train MAE: 0.07 | Val Loss: 0.0048 | Val MAE: 0.05 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.004773. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0049 | Train MAE: 0.05 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.002662. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0046 | Train MAE: 0.05 | Val Loss: 0.0033 | Val MAE: 0.04 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0039 | Train MAE: 0.05 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.002457. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0038 | Train MAE: 0.05 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0036 | Train MAE: 0.05 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 7.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0037 | Train MAE: 0.05 | Val Loss: 0.0033 | Val MAE: 0.05 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0038 | Train MAE: 0.05 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0036 | Train MAE: 0.05 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0029

🔁 Trial 2
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00873
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0061 | Train MAE: 0.05 | Val Loss: 0.0035 | Val MAE: 0.04 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.003546. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.002320. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.002165. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.002008. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0484 | Train MAE: 0.17 | Val Loss: 0.0540 | Val MAE: 0.20 | ⏱️ Time: 7.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0478 | Train MAE: 0.18 | Val Loss: 0.0542 | Val MAE: 0.20 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0491 | Train MAE: 0.18 | Val Loss: 0.0559 | Val MAE: 0.19 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0484 | Train MAE: 0.18 | Val Loss: 0.0548 | Val MAE: 0.19 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0478 | Train MAE: 0.18 | Val Loss: 0.0628 | Val MAE: 0.19 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0628

🔁 Trial 3
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00872
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0471 | Train MAE: 0.18 | Val Loss: 0.0553 | Val MAE: 0.20 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.055270. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0459 | Train MAE: 0.18 | Val Loss: 0.0548 | Val MAE: 0.19 | ⏱️ Time: 7.4s
✅ Mejor val_loss: 0.054805. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0456 | Train MAE: 0.18 | Val Loss: 0.0542 | Val MAE: 0.20 | ⏱️ Time: 7.8s
✅ Mejor val_loss: 0.054179. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0455 | Train MAE: 0.18 | Val Loss: 0.0549 | Val MAE: 0.19 | ⏱️ Time: 7.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0457 | Train MAE: 0.18 | Val Loss: 0.0543 | Val MAE: 0.20 | ⏱️ Time: 7.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0457 | Train MAE: 0.18 | Val Loss: 0.0542 | Val MAE: 0.20 | ⏱️ Time: 7.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0457 | Train MAE: 0.18 | Val Loss: 0.0542 | Val MAE: 0.20 | ⏱️ Time: 7.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0457 | Train MAE: 0.18 | Val Loss: 0.0542 | Val MAE: 0.20 | ⏱️ Time: 7.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0542

🔁 Trial 4
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00830
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0056 | Train MAE: 0.05 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.002556. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0031 | Val MAE: 0.05 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.002483. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0443 | Train MAE: 0.14 | Val Loss: 0.0552 | Val MAE: 0.20 | ⏱️ Time: 7.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0499 | Train MAE: 0.18 | Val Loss: 0.0590 | Val MAE: 0.19 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0477 | Train MAE: 0.18 | Val Loss: 0.0547 | Val MAE: 0.20 | ⏱️ Time: 7.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0485 | Train MAE: 0.18 | Val Loss: 0.0589 | Val MAE: 0.21 | ⏱️ Time: 7.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0477 | Train MAE: 0.18 | Val Loss: 0.0556 | Val MAE: 0.21 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0556

🔁 Trial 5
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00676
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0063 | Train MAE: 0.06 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.002332. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.002254. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.002145. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.002133. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.001922. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 7.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0021

🔁 Trial 6
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00991
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0091 | Train MAE: 0.07 | Val Loss: 0.0035 | Val MAE: 0.05 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.003462. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0048 | Train MAE: 0.05 | Val Loss: 0.0033 | Val MAE: 0.05 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.003255. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.002948. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0039 | Val MAE: 0.04 | ⏱️ Time: 7.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0044 | Train MAE: 0.05 | Val Loss: 0.0042 | Val MAE: 0.05 | ⏱️ Time: 7.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 7.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0043 | Train MAE: 0.05 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0043 | Train MAE: 0.05 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0032

🔁 Trial 7
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00866
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0140 | Train MAE: 0.08 | Val Loss: 0.0026 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.002594. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.002225. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.002170. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0036 | Val MAE: 0.05 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0117 | Train MAE: 0.07 | Val Loss: 0.0568 | Val MAE: 0.18 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0459 | Train MAE: 0.18 | Val Loss: 0.0489 | Val MAE: 0.19 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0489

🔁 Trial 8
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00501
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0121 | Train MAE: 0.07 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.003006. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002833. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.002486. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002377. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.002224. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001947. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0021

🔁 Trial 9
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00501
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0486 | Train MAE: 0.18 | Val Loss: 0.0177 | Val MAE: 0.09 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.017689. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0074 | Train MAE: 0.07 | Val Loss: 0.0040 | Val MAE: 0.05 | ⏱️ Time: 7.7s
✅ Mejor val_loss: 0.003982. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0050 | Train MAE: 0.05 | Val Loss: 0.0054 | Val MAE: 0.05 | ⏱️ Time: 7.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0049 | Train MAE: 0.05 | Val Loss: 0.0035 | Val MAE: 0.04 | ⏱️ Time: 7.7s
✅ Mejor val_loss: 0.003451. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0046 | Train MAE: 0.05 | Val Loss: 0.0037 | Val MAE: 0.05 | ⏱️ Time: 7.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0033 | Val MAE: 0.04 | ⏱️ Time: 7.7s
✅ Mejor val_loss: 0.003279. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0043 | Train MAE: 0.05 | Val Loss: 0.0033 | Val MAE: 0.04 | ⏱️ Time: 7.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0042 | Train MAE: 0.05 | Val Loss: 0.0037 | Val MAE: 0.04 | ⏱️ Time: 7.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0040 | Val MAE: 0.05 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0040 | Train MAE: 0.05 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.002911. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0038 | Train MAE: 0.05 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 7.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0038 | Train MAE: 0.05 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 7.7s
✅ Mejor val_loss: 0.002865. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0038 | Train MAE: 0.05 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 7.7s
✅ Mejor val_loss: 0.002473. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0036 | Train MAE: 0.05 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 7.7s
✅ Mejor val_loss: 0.002250. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0035 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 7.9s
✅ Mejor val_loss: 0.002214. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0036 | Train MAE: 0.05 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 7.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0036 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 7.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 7.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0035 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 7.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0035 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 7.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 20 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0023

🔁 Trial 10
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00510
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0102 | Train MAE: 0.07 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 7.4s
✅ Mejor val_loss: 0.002935. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 7.4s
✅ Mejor val_loss: 0.002703. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.4s
✅ Mejor val_loss: 0.002090. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 7.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 7.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 7.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 7.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0024

🔁 Trial 11
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00621
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0506 | Train MAE: 0.19 | Val Loss: 0.0546 | Val MAE: 0.19 | ⏱️ Time: 7.4s
✅ Mejor val_loss: 0.054601. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0459 | Train MAE: 0.18 | Val Loss: 0.0545 | Val MAE: 0.20 | ⏱️ Time: 7.4s
✅ Mejor val_loss: 0.054504. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0410 | Train MAE: 0.17 | Val Loss: 0.0050 | Val MAE: 0.05 | ⏱️ Time: 7.4s
✅ Mejor val_loss: 0.005021. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.002655. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002385. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002249. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0038 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002162. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 7.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.4s
✅ Mejor val_loss: 0.002070. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 7.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.002014. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 7.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 7.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 22 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0026

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 32
   - num_layers: 2
   - lr: 0.0050090744643500225


📍 Parking 7 | 🧠 Modelo: RNN
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0132 | Train MAE: 0.08 | Val Loss: 0.0050 | Val MAE: 0.04 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.004952. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0033 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.003291. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.03 | Val Loss: 0.0027 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001910. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.

🧪 Optimizando RNN con Optuna para parking 7...


🔁 Trial 0
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00811
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0354 | Train MAE: 0.15 | Val Loss: 0.0316 | Val MAE: 0.14 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.031641. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0312 | Train MAE: 0.14 | Val Loss: 0.0296 | Val MAE: 0.14 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.029589. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0103 | Train MAE: 0.07 | Val Loss: 0.0033 | Val MAE: 0.04 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.003287. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001464. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001387. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0190 | Train MAE: 0.09 | Val Loss: 0.0271 | Val MAE: 0.14 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0302 | Train MAE: 0.14 | Val Loss: 0.0354 | Val MAE: 0.17 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0295 | Train MAE: 0.14 | Val Loss: 0.0276 | Val MAE: 0.13 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0276

🔁 Trial 1
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00640
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0109 | Train MAE: 0.07 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001962. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.001555. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0129 | Train MAE: 0.08 | Val Loss: 0.0177 | Val MAE: 0.10 | ⏱️ Time: 7.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0242 | Train MAE: 0.12 | Val Loss: 0.0186 | Val MAE: 0.10 | ⏱️ Time: 7.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0189 | Train MAE: 0.10 | Val Loss: 0.0189 | Val MAE: 0.10 | ⏱️ Time: 7.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0188 | Train MAE: 0.10 | Val Loss: 0.0186 | Val MAE: 0.10 | ⏱️ Time: 7.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0186

🔁 Trial 2
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00761
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0141 | Train MAE: 0.08 | Val Loss: 0.0028 | Val MAE: 0.03 | ⏱️ Time: 7.4s
✅ Mejor val_loss: 0.002831. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001778. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001506. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0017

🔁 Trial 3
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00754
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0053 | Train MAE: 0.05 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.6s
✅ Mejor val_loss: 0.001812. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.8s
✅ Mejor val_loss: 0.001796. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 7.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 7.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.6s
✅ Mejor val_loss: 0.001575. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001546. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001340. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0018

🔁 Trial 4
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00509
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0148 | Train MAE: 0.08 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.002957. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.002127. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001599. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001516. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001500. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001463. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001411. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001331. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.04 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001271. Guardando modelo...

📊 Epoch 22/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 26/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001247. Guardando modelo...

📊 Epoch 27/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 28/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 29/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 30/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora
🎯 Resultado trial 4 → val_loss = 0.0012

🔁 Trial 5
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.01000
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0260 | Train MAE: 0.12 | Val Loss: 0.0027 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.002745. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0040 | Train MAE: 0.05 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.002314. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001805. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001648. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0027

🔁 Trial 6
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00996
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0212 | Train MAE: 0.11 | Val Loss: 0.0041 | Val MAE: 0.06 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.004108. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0037 | Train MAE: 0.05 | Val Loss: 0.0026 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.002611. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001997. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001618. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.001511. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.001219. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 15 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0023

🔁 Trial 7
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00503
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0174 | Train MAE: 0.10 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.002682. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001625. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 7 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0019

🔁 Trial 8
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00691
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0343 | Train MAE: 0.15 | Val Loss: 0.0302 | Val MAE: 0.14 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.030211. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0309 | Train MAE: 0.14 | Val Loss: 0.0299 | Val MAE: 0.15 | ⏱️ Time: 7.7s
✅ Mejor val_loss: 0.029947. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0312 | Train MAE: 0.14 | Val Loss: 0.0312 | Val MAE: 0.14 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0308 | Train MAE: 0.14 | Val Loss: 0.0308 | Val MAE: 0.14 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0310 | Train MAE: 0.14 | Val Loss: 0.0298 | Val MAE: 0.15 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.029761. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0308 | Train MAE: 0.14 | Val Loss: 0.0297 | Val MAE: 0.14 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.029671. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0306 | Train MAE: 0.14 | Val Loss: 0.0317 | Val MAE: 0.14 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0309 | Train MAE: 0.14 | Val Loss: 0.0297 | Val MAE: 0.14 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0309 | Train MAE: 0.14 | Val Loss: 0.0305 | Val MAE: 0.15 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0312 | Train MAE: 0.14 | Val Loss: 0.0304 | Val MAE: 0.15 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0309 | Train MAE: 0.14 | Val Loss: 0.0307 | Val MAE: 0.14 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0307

🔁 Trial 9
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00752
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0328 | Train MAE: 0.15 | Val Loss: 0.0297 | Val MAE: 0.15 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.029734. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0310 | Train MAE: 0.14 | Val Loss: 0.0298 | Val MAE: 0.14 | ⏱️ Time: 7.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0307 | Train MAE: 0.14 | Val Loss: 0.0300 | Val MAE: 0.14 | ⏱️ Time: 7.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0309 | Train MAE: 0.14 | Val Loss: 0.0298 | Val MAE: 0.15 | ⏱️ Time: 7.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0309 | Train MAE: 0.14 | Val Loss: 0.0311 | Val MAE: 0.14 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0308 | Train MAE: 0.14 | Val Loss: 0.0303 | Val MAE: 0.14 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 6 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0303

🔁 Trial 10
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00502
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0181 | Train MAE: 0.09 | Val Loss: 0.0036 | Val MAE: 0.04 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.003590. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001890. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001609. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001568. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001544. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001476. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001378. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001316. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001278. Guardando modelo...

📊 Epoch 20/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001227. Guardando modelo...

📊 Epoch 23/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 26/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 27/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 27 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0013

🔁 Trial 11
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00501
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0114 | Train MAE: 0.07 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.002495. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001593. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001515. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001501. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001401. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001383. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001348. Guardando modelo...

📊 Epoch 20/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001310. Guardando modelo...

📊 Epoch 23/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001175. Guardando modelo...

📊 Epoch 25/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 26/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 27/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 28/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 29/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 29 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0015

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 16
   - num_layers: 2
   - lr: 0.005093444104457478


📍 Parking 8 | 🧠 Modelo: RNN
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0131 | Train MAE: 0.07 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 10.1s
✅ Mejor val_loss: 0.002948. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0026 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 10.1s
✅ Mejor val_loss: 0.001577. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 7 por falta de mejora.

🧪 Optimizando RNN con Optuna para parking 8...


🔁 Trial 0
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00669
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0079 | Train MAE: 0.06 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.001684. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.001158. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.001018. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.000944. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0010

🔁 Trial 1
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00743
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0054 | Train MAE: 0.05 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.001052. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.2s
✅ Mejor val_loss: 0.001013. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 11.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.000896. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0064 | Train MAE: 0.05 | Val Loss: 0.0040 | Val MAE: 0.04 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0036 | Train MAE: 0.05 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0015

🔁 Trial 2
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00763
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0115 | Train MAE: 0.07 | Val Loss: 0.0031 | Val MAE: 0.05 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.003126. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.001304. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0030 | Val MAE: 0.05 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 11.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 11.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 7 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0013

🔁 Trial 3
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00605
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0057 | Train MAE: 0.06 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 11.8s
✅ Mejor val_loss: 0.001341. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 11.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.04 | ⏱️ Time: 12.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.001063. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.001020. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.000898. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 11.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0015

🔁 Trial 4
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00742
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0509 | Train MAE: 0.18 | Val Loss: 0.0066 | Val MAE: 0.06 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.006604. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0113 | Train MAE: 0.08 | Val Loss: 0.0096 | Val MAE: 0.08 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0072 | Train MAE: 0.07 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.002963. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0046 | Train MAE: 0.05 | Val Loss: 0.0047 | Val MAE: 0.06 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0040 | Train MAE: 0.05 | Val Loss: 0.0032 | Val MAE: 0.05 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.002643. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0042 | Val MAE: 0.06 | ⏱️ Time: 12.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.05 | ⏱️ Time: 12.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0099 | Train MAE: 0.07 | Val Loss: 0.0048 | Val MAE: 0.06 | ⏱️ Time: 12.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0061 | Train MAE: 0.06 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.002386. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 11.2s
✅ Mejor val_loss: 0.001431. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0047 | Val MAE: 0.06 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0040 | Train MAE: 0.05 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 11.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0039 | Train MAE: 0.05 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0017

🔁 Trial 5
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00803
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0066 | Train MAE: 0.05 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.000929. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 6 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0012

🔁 Trial 6
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00686
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0078 | Train MAE: 0.06 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.001012. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.000976. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.7s
✅ Mejor val_loss: 0.000891. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.8s
✅ Mejor val_loss: 0.000862. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 12.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 11.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0011

🔁 Trial 7
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00564
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0045 | Train MAE: 0.04 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.001013. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 6 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0011

🔁 Trial 8
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00670
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0182 | Train MAE: 0.09 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 11.2s
✅ Mejor val_loss: 0.002252. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.001138. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.001037. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 12.3s
✅ Mejor val_loss: 0.000993. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 12.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 12.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 12.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 12.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 12.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0011

🔁 Trial 9
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00861
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0073 | Train MAE: 0.06 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 12.2s
✅ Mejor val_loss: 0.001725. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 12.2s
✅ Mejor val_loss: 0.001312. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 12.2s
✅ Mejor val_loss: 0.000897. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 12.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 12.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 12.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 12.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 12.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0025

🔁 Trial 10
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00973
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0262 | Train MAE: 0.12 | Val Loss: 0.0192 | Val MAE: 0.12 | ⏱️ Time: 11.9s
✅ Mejor val_loss: 0.019170. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0330 | Train MAE: 0.14 | Val Loss: 0.0173 | Val MAE: 0.10 | ⏱️ Time: 11.8s
✅ Mejor val_loss: 0.017322. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0143 | Train MAE: 0.10 | Val Loss: 0.0149 | Val MAE: 0.11 | ⏱️ Time: 11.8s
✅ Mejor val_loss: 0.014927. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0106 | Train MAE: 0.08 | Val Loss: 0.0058 | Val MAE: 0.05 | ⏱️ Time: 11.8s
✅ Mejor val_loss: 0.005754. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0088 | Train MAE: 0.07 | Val Loss: 0.0067 | Val MAE: 0.07 | ⏱️ Time: 11.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0087 | Train MAE: 0.07 | Val Loss: 0.0048 | Val MAE: 0.05 | ⏱️ Time: 11.8s
✅ Mejor val_loss: 0.004769. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0088 | Train MAE: 0.07 | Val Loss: 0.0042 | Val MAE: 0.05 | ⏱️ Time: 12.1s
✅ Mejor val_loss: 0.004205. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0089 | Train MAE: 0.07 | Val Loss: 0.0044 | Val MAE: 0.05 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0096 | Train MAE: 0.08 | Val Loss: 0.0112 | Val MAE: 0.10 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0089 | Train MAE: 0.07 | Val Loss: 0.0040 | Val MAE: 0.05 | ⏱️ Time: 10.8s
✅ Mejor val_loss: 0.004012. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0096 | Train MAE: 0.08 | Val Loss: 0.0086 | Val MAE: 0.08 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0098 | Train MAE: 0.08 | Val Loss: 0.0043 | Val MAE: 0.05 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0088 | Train MAE: 0.07 | Val Loss: 0.0078 | Val MAE: 0.07 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0096 | Train MAE: 0.08 | Val Loss: 0.0098 | Val MAE: 0.08 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0089 | Train MAE: 0.07 | Val Loss: 0.0046 | Val MAE: 0.06 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 15 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0046

🔁 Trial 11
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00638
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0170 | Train MAE: 0.08 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.001017. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 6 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0014

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 16
   - num_layers: 2
   - lr: 0.006690218580442006


📍 Parking 13 | 🧠 Modelo: RNN
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0080 | Train MAE: 0.06 | Val Loss: 0.0030 | Val MAE: 0.03 | ⏱️ Time: 6.2s
✅ Mejor val_loss: 0.003011. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.1s
✅ Mejor val_loss: 0.001865. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 7 por falta de mejora.

🧪 Optimizando RNN con Optuna para parking 13...


🔁 Trial 0
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00637
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0137 | Train MAE: 0.08 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.002885. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001871. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001343. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001281. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001154. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.000975. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0015

🔁 Trial 1
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00883
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0066 | Train MAE: 0.05 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001138. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001067. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001054. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001006. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.04 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0011

🔁 Trial 2
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00743
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0292 | Train MAE: 0.14 | Val Loss: 0.0202 | Val MAE: 0.11 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.020227. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0209 | Train MAE: 0.12 | Val Loss: 0.0219 | Val MAE: 0.12 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0207 | Train MAE: 0.12 | Val Loss: 0.0160 | Val MAE: 0.10 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.015984. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0207 | Train MAE: 0.12 | Val Loss: 0.0209 | Val MAE: 0.11 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0287 | Train MAE: 0.14 | Val Loss: 0.0354 | Val MAE: 0.14 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0309 | Train MAE: 0.14 | Val Loss: 0.0230 | Val MAE: 0.12 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0310 | Train MAE: 0.14 | Val Loss: 0.0281 | Val MAE: 0.13 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0309 | Train MAE: 0.14 | Val Loss: 0.0240 | Val MAE: 0.12 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0240

🔁 Trial 3
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00939
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0311 | Train MAE: 0.14 | Val Loss: 0.0045 | Val MAE: 0.05 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.004500. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0035 | Train MAE: 0.04 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001305. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001036. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.000853. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0012

🔁 Trial 4
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00966
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0073 | Train MAE: 0.05 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.3s
✅ Mejor val_loss: 0.001207. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.3s
✅ Mejor val_loss: 0.001062. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.000952. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000850. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000713. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0019

🔁 Trial 5
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00607
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0058 | Train MAE: 0.05 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001196. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 6 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0013

🔁 Trial 6
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00904
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0068 | Train MAE: 0.05 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.002537. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001102. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001027. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.000945. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000927. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0345 | Train MAE: 0.13 | Val Loss: 0.0222 | Val MAE: 0.12 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0336 | Train MAE: 0.15 | Val Loss: 0.0257 | Val MAE: 0.12 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0334 | Train MAE: 0.15 | Val Loss: 0.0452 | Val MAE: 0.17 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0337 | Train MAE: 0.15 | Val Loss: 0.0647 | Val MAE: 0.21 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0337 | Train MAE: 0.15 | Val Loss: 0.0278 | Val MAE: 0.12 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 19 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0278

🔁 Trial 7
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00732
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0046 | Train MAE: 0.05 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001193. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0215 | Train MAE: 0.11 | Val Loss: 0.0235 | Val MAE: 0.12 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0253 | Train MAE: 0.13 | Val Loss: 0.0200 | Val MAE: 0.12 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0250 | Train MAE: 0.13 | Val Loss: 0.0223 | Val MAE: 0.12 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 6 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0223

🔁 Trial 8
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00632
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0062 | Train MAE: 0.05 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001211. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.3s
✅ Mejor val_loss: 0.001030. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.3s
✅ Mejor val_loss: 0.000992. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.3s
✅ Mejor val_loss: 0.000962. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.000894. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.04 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.000869. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.000836. Guardando modelo...

📊 Epoch 20/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.000729. Guardando modelo...

📊 Epoch 21/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.000692. Guardando modelo...

📊 Epoch 23/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 26/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 27/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 27 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0008

🔁 Trial 9
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00974
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0079 | Train MAE: 0.06 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001395. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001287. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001122. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001055. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.000989. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0103 | Train MAE: 0.06 | Val Loss: 0.0292 | Val MAE: 0.13 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0320 | Train MAE: 0.15 | Val Loss: 0.0285 | Val MAE: 0.13 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0314 | Train MAE: 0.14 | Val Loss: 0.0294 | Val MAE: 0.13 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0294

🔁 Trial 10
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00501
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0074 | Train MAE: 0.06 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001558. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001076. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.000994. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.000963. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0010

🔁 Trial 11
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00505
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0141 | Train MAE: 0.07 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001860. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001326. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.3s
✅ Mejor val_loss: 0.001246. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.3s
✅ Mejor val_loss: 0.000980. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.000960. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0010

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 32
   - num_layers: 2
   - lr: 0.006317672794523644


📍 Parking 34 | 🧠 Modelo: RNN
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0072 | Train MAE: 0.06 | Val Loss: 0.0036 | Val MAE: 0.04 | ⏱️ Time: 4.1s
✅ Mejor val_loss: 0.003613. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 4.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.2s
✅ Mejor val_loss: 0.001937. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.

🧪 Optimizando RNN con Optuna para parking 34...


🔁 Trial 0
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00987
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0095 | Train MAE: 0.06 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.002173. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001778. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001470. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001440. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001037. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0015

🔁 Trial 1
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00578
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0303 | Train MAE: 0.16 | Val Loss: 0.0324 | Val MAE: 0.16 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.032437. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0285 | Train MAE: 0.15 | Val Loss: 0.0329 | Val MAE: 0.16 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0285 | Train MAE: 0.15 | Val Loss: 0.0327 | Val MAE: 0.16 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0284 | Train MAE: 0.15 | Val Loss: 0.0332 | Val MAE: 0.16 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0284 | Train MAE: 0.15 | Val Loss: 0.0327 | Val MAE: 0.17 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0285 | Train MAE: 0.15 | Val Loss: 0.0332 | Val MAE: 0.16 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 6 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0332

🔁 Trial 2
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00977
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0090 | Train MAE: 0.06 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.003128. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001396. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001368. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001189. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0269 | Train MAE: 0.12 | Val Loss: 0.0339 | Val MAE: 0.17 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0339

🔁 Trial 3
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00892
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0183 | Train MAE: 0.10 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.002296. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.002200. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001749. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001726. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001487. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001321. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001285. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001128. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 19 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0012

🔁 Trial 4
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00675
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0112 | Train MAE: 0.08 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.002060. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001566. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001326. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001181. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0014

🔁 Trial 5
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00520
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0395 | Train MAE: 0.17 | Val Loss: 0.0325 | Val MAE: 0.16 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.032523. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0286 | Train MAE: 0.15 | Val Loss: 0.0327 | Val MAE: 0.16 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0286 | Train MAE: 0.15 | Val Loss: 0.0325 | Val MAE: 0.16 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0286 | Train MAE: 0.15 | Val Loss: 0.0328 | Val MAE: 0.16 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0285 | Train MAE: 0.15 | Val Loss: 0.0325 | Val MAE: 0.16 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0285 | Train MAE: 0.15 | Val Loss: 0.0328 | Val MAE: 0.17 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 6 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0328

🔁 Trial 6
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00878
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0119 | Train MAE: 0.08 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001870. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001793. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001733. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001429. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0018

🔁 Trial 7
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00556
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0101 | Train MAE: 0.07 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 4.2s
✅ Mejor val_loss: 0.002459. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.002098. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001804. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001500. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001441. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001421. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001345. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001180. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001079. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.000977. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 21 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0010

🔁 Trial 8
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00841
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0094 | Train MAE: 0.07 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.003079. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001562. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001522. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001332. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001305. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0014

🔁 Trial 9
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00715
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0234 | Train MAE: 0.11 | Val Loss: 0.0042 | Val MAE: 0.05 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.004153. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0051 | Train MAE: 0.06 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.002836. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0038 | Train MAE: 0.05 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001801. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001747. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001543. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001483. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 19 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0020

🔁 Trial 10
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00602
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0115 | Train MAE: 0.08 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.002758. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.002077. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001996. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001768. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001441. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001335. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001164. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001118. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.000988. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 19 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0014

🔁 Trial 11
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00757
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0089 | Train MAE: 0.06 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.002266. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001916. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001880. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001741. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001503. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001427. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001387. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001270. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001182. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001049. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.000970. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 21 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0013

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 16
   - num_layers: 2
   - lr: 0.0055611624718106415


📍 Parking 75 | 🧠 Modelo: RNN
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0107 | Train MAE: 0.07 | Val Loss: 0.0037 | Val MAE: 0.04 | ⏱️ Time: 10.3s
✅ Mejor val_loss: 0.003690. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.1s
✅ Mejor val_loss: 0.002613. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 10.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 10.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 10.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 7 por falta de mejora.

🧪 Optimizando RNN con Optuna para parking 75...


🔁 Trial 0
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00722
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0335 | Train MAE: 0.15 | Val Loss: 0.0172 | Val MAE: 0.10 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.017178. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0134 | Train MAE: 0.09 | Val Loss: 0.0068 | Val MAE: 0.07 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.006821. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0084 | Train MAE: 0.07 | Val Loss: 0.0041 | Val MAE: 0.05 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.004075. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0051 | Train MAE: 0.05 | Val Loss: 0.0033 | Val MAE: 0.04 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.003294. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0046 | Train MAE: 0.05 | Val Loss: 0.0037 | Val MAE: 0.05 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0128 | Train MAE: 0.08 | Val Loss: 0.0073 | Val MAE: 0.07 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0106 | Train MAE: 0.08 | Val Loss: 0.0076 | Val MAE: 0.07 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0079 | Train MAE: 0.07 | Val Loss: 0.0064 | Val MAE: 0.06 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0078 | Train MAE: 0.07 | Val Loss: 0.0051 | Val MAE: 0.06 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0051

🔁 Trial 1
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00592
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0067 | Train MAE: 0.06 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.003205. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0039 | Train MAE: 0.05 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 10.3s
✅ Mejor val_loss: 0.002672. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 10.3s
✅ Mejor val_loss: 0.002387. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 10.3s
✅ Mejor val_loss: 0.002330. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.002258. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.3s
✅ Mejor val_loss: 0.002219. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.3s
✅ Mejor val_loss: 0.002161. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.3s
✅ Mejor val_loss: 0.002064. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.002052. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.001992. Guardando modelo...

📊 Epoch 22/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 26/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.001821. Guardando modelo...

📊 Epoch 27/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 28/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 29/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 30/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 4/5 sin mejora
🎯 Resultado trial 1 → val_loss = 0.0020

🔁 Trial 2
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00731
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0095 | Train MAE: 0.07 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 10.3s
✅ Mejor val_loss: 0.003126. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0038 | Train MAE: 0.05 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 10.3s
✅ Mejor val_loss: 0.002691. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0034 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.002495. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.002350. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 10.3s
✅ Mejor val_loss: 0.002227. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0028

🔁 Trial 3
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00589
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0307 | Train MAE: 0.13 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 10.8s
✅ Mejor val_loss: 0.003069. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0039 | Train MAE: 0.05 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 10.7s
✅ Mejor val_loss: 0.002522. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 10.8s
✅ Mejor val_loss: 0.002274. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0024

🔁 Trial 4
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00827
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0069 | Train MAE: 0.06 | Val Loss: 0.0033 | Val MAE: 0.04 | ⏱️ Time: 10.8s
✅ Mejor val_loss: 0.003290. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0040 | Train MAE: 0.05 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.002933. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0037 | Train MAE: 0.05 | Val Loss: 0.0042 | Val MAE: 0.05 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0037 | Train MAE: 0.05 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0036 | Train MAE: 0.05 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0035 | Train MAE: 0.04 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0035 | Train MAE: 0.05 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 7 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0032

🔁 Trial 5
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00703
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0088 | Train MAE: 0.07 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.003227. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0046 | Train MAE: 0.05 | Val Loss: 0.0040 | Val MAE: 0.05 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0038 | Train MAE: 0.05 | Val Loss: 0.0033 | Val MAE: 0.04 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.002808. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 10.3s
✅ Mejor val_loss: 0.002768. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.3s
✅ Mejor val_loss: 0.002555. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.2s
✅ Mejor val_loss: 0.002189. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0024

🔁 Trial 6
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00576
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0068 | Train MAE: 0.06 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 10.7s
✅ Mejor val_loss: 0.002762. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 10.7s
✅ Mejor val_loss: 0.002680. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0035 | Val MAE: 0.04 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.8s
✅ Mejor val_loss: 0.002599. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0271 | Train MAE: 0.12 | Val Loss: 0.0437 | Val MAE: 0.18 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0506 | Train MAE: 0.20 | Val Loss: 0.0433 | Val MAE: 0.18 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0506 | Train MAE: 0.20 | Val Loss: 0.0451 | Val MAE: 0.19 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0501 | Train MAE: 0.20 | Val Loss: 0.0452 | Val MAE: 0.19 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0502 | Train MAE: 0.20 | Val Loss: 0.0446 | Val MAE: 0.19 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0446

🔁 Trial 7
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00580
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0122 | Train MAE: 0.08 | Val Loss: 0.0039 | Val MAE: 0.05 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.003939. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0051 | Train MAE: 0.05 | Val Loss: 0.0038 | Val MAE: 0.05 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.003792. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0047 | Train MAE: 0.05 | Val Loss: 0.0034 | Val MAE: 0.04 | ⏱️ Time: 11.2s
✅ Mejor val_loss: 0.003399. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0043 | Train MAE: 0.05 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 11.2s
✅ Mejor val_loss: 0.002954. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0042 | Train MAE: 0.05 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0042 | Train MAE: 0.05 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0034 | Val MAE: 0.05 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0040 | Train MAE: 0.05 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0040 | Train MAE: 0.05 | Val Loss: 0.0032 | Val MAE: 0.05 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0032

🔁 Trial 8
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00747
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0268 | Train MAE: 0.13 | Val Loss: 0.0044 | Val MAE: 0.05 | ⏱️ Time: 11.1s
✅ Mejor val_loss: 0.004381. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0064 | Train MAE: 0.06 | Val Loss: 0.0040 | Val MAE: 0.05 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.003970. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0054 | Train MAE: 0.06 | Val Loss: 0.0038 | Val MAE: 0.04 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.003763. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0048 | Train MAE: 0.05 | Val Loss: 0.0033 | Val MAE: 0.04 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.003334. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0047 | Train MAE: 0.05 | Val Loss: 0.0038 | Val MAE: 0.05 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0047 | Train MAE: 0.05 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.003022. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0046 | Train MAE: 0.05 | Val Loss: 0.0039 | Val MAE: 0.05 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0033 | Val MAE: 0.04 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0038 | Val MAE: 0.05 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0044 | Train MAE: 0.05 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0043 | Train MAE: 0.05 | Val Loss: 0.0045 | Val MAE: 0.06 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0045

🔁 Trial 9
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00955
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0096 | Train MAE: 0.07 | Val Loss: 0.0039 | Val MAE: 0.04 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.003855. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0054 | Train MAE: 0.06 | Val Loss: 0.0042 | Val MAE: 0.05 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0049 | Train MAE: 0.05 | Val Loss: 0.0039 | Val MAE: 0.05 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0046 | Train MAE: 0.05 | Val Loss: 0.0037 | Val MAE: 0.05 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.003722. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0042 | Val MAE: 0.05 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0033 | Val MAE: 0.04 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.003323. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 11.1s
✅ Mejor val_loss: 0.003177. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0044 | Train MAE: 0.05 | Val Loss: 0.0033 | Val MAE: 0.05 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.002930. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0045 | Val MAE: 0.05 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0044 | Train MAE: 0.05 | Val Loss: 0.0041 | Val MAE: 0.05 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0044 | Train MAE: 0.05 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 11.1s
✅ Mejor val_loss: 0.002750. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0044 | Train MAE: 0.05 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0042 | Train MAE: 0.05 | Val Loss: 0.0039 | Val MAE: 0.04 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0043 | Train MAE: 0.05 | Val Loss: 0.0045 | Val MAE: 0.05 | ⏱️ Time: 11.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0042 | Train MAE: 0.05 | Val Loss: 0.0034 | Val MAE: 0.04 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0044 | Train MAE: 0.05 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0029

🔁 Trial 10
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00510
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0123 | Train MAE: 0.07 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.003027. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0040 | Train MAE: 0.05 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.002880. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.002540. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.002229. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.002105. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0034 | Val MAE: 0.05 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0023

🔁 Trial 11
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00508
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0089 | Train MAE: 0.06 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 10.3s
✅ Mejor val_loss: 0.002997. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0035 | Train MAE: 0.04 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.002416. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.002119. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0023

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 16
   - num_layers: 2
   - lr: 0.005919916444099004


📍 Parking 77 | 🧠 Modelo: RNN
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0205 | Train MAE: 0.11 | Val Loss: 0.0076 | Val MAE: 0.07 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.007572. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0050 | Train MAE: 0.05 | Val Loss: 0.0045 | Val MAE: 0.05 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.004532. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0033 | Val MAE: 0.04 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.003266. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.002224. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.

🧪 Optimizando RNN con Optuna para parking 77...


🔁 Trial 0
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00658
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0074 | Train MAE: 0.06 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.002575. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 4.9s
✅ Mejor val_loss: 0.002443. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 4.9s
✅ Mejor val_loss: 0.002179. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 4.9s
✅ Mejor val_loss: 0.002162. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.9s
✅ Mejor val_loss: 0.001973. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.9s
✅ Mejor val_loss: 0.001940. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 20 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0022

🔁 Trial 1
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00588
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0140 | Train MAE: 0.08 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 4.9s
✅ Mejor val_loss: 0.002617. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 4.9s
✅ Mejor val_loss: 0.002368. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 4.9s
✅ Mejor val_loss: 0.002079. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.9s
✅ Mejor val_loss: 0.002049. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.9s
✅ Mejor val_loss: 0.002002. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 19 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0025

🔁 Trial 2
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00776
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0138 | Train MAE: 0.08 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002695. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0036 | Train MAE: 0.05 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.002321. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002268. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002186. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0030 | Val MAE: 0.05 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0023

🔁 Trial 3
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00536
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0219 | Train MAE: 0.11 | Val Loss: 0.0037 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.003652. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002412. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002241. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0023

🔁 Trial 4
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00943
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0087 | Train MAE: 0.06 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 4.9s
✅ Mejor val_loss: 0.002361. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.9s
✅ Mejor val_loss: 0.002029. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.9s
✅ Mejor val_loss: 0.001962. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0038 | Val MAE: 0.05 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0519 | Train MAE: 0.17 | Val Loss: 0.0469 | Val MAE: 0.18 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0469

🔁 Trial 5
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00639
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0539 | Train MAE: 0.19 | Val Loss: 0.0453 | Val MAE: 0.19 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.045295. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0403 | Train MAE: 0.17 | Val Loss: 0.0453 | Val MAE: 0.19 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0402 | Train MAE: 0.17 | Val Loss: 0.0454 | Val MAE: 0.19 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0401 | Train MAE: 0.17 | Val Loss: 0.0453 | Val MAE: 0.19 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.045253. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0402 | Train MAE: 0.17 | Val Loss: 0.0455 | Val MAE: 0.19 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0401 | Train MAE: 0.17 | Val Loss: 0.0462 | Val MAE: 0.19 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0400 | Train MAE: 0.17 | Val Loss: 0.0457 | Val MAE: 0.19 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0401 | Train MAE: 0.17 | Val Loss: 0.0455 | Val MAE: 0.19 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0400 | Train MAE: 0.17 | Val Loss: 0.0453 | Val MAE: 0.19 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0453

🔁 Trial 6
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00995
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0117 | Train MAE: 0.08 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.002473. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0036 | Train MAE: 0.05 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0035 | Train MAE: 0.05 | Val Loss: 0.0035 | Val MAE: 0.05 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0033 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002279. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0038 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0032 | Val MAE: 0.05 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0138 | Train MAE: 0.08 | Val Loss: 0.0434 | Val MAE: 0.18 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0399 | Train MAE: 0.17 | Val Loss: 0.0474 | Val MAE: 0.18 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0474

🔁 Trial 7
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00723
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0162 | Train MAE: 0.09 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.002766. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0047 | Train MAE: 0.05 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.002672. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0043 | Train MAE: 0.05 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0043 | Train MAE: 0.05 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.002498. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0038 | Train MAE: 0.05 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.002402. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0037 | Train MAE: 0.05 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.002341. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0037 | Train MAE: 0.05 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0037 | Train MAE: 0.05 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0036 | Train MAE: 0.05 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0035 | Train MAE: 0.05 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0036 | Train MAE: 0.05 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0029

🔁 Trial 8
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00642
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0341 | Train MAE: 0.14 | Val Loss: 0.0475 | Val MAE: 0.18 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.047529. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0406 | Train MAE: 0.17 | Val Loss: 0.0420 | Val MAE: 0.18 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.042026. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0183 | Train MAE: 0.11 | Val Loss: 0.0087 | Val MAE: 0.08 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.008711. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0090 | Train MAE: 0.08 | Val Loss: 0.0049 | Val MAE: 0.05 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.004935. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0085 | Train MAE: 0.07 | Val Loss: 0.0064 | Val MAE: 0.06 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0064 | Train MAE: 0.06 | Val Loss: 0.0046 | Val MAE: 0.05 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.004576. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0061 | Train MAE: 0.06 | Val Loss: 0.0034 | Val MAE: 0.04 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.003397. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0049 | Train MAE: 0.05 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.003204. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0054 | Train MAE: 0.06 | Val Loss: 0.0056 | Val MAE: 0.06 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0054 | Train MAE: 0.06 | Val Loss: 0.0033 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0043 | Train MAE: 0.05 | Val Loss: 0.0040 | Val MAE: 0.05 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0049 | Train MAE: 0.05 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002961. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.002358. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0039 | Val MAE: 0.05 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0042 | Train MAE: 0.05 | Val Loss: 0.0036 | Val MAE: 0.05 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.002317. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0037 | Train MAE: 0.05 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0035 | Train MAE: 0.05 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0035 | Train MAE: 0.05 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0218 | Train MAE: 0.10 | Val Loss: 0.0320 | Val MAE: 0.14 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0159 | Train MAE: 0.10 | Val Loss: 0.0069 | Val MAE: 0.06 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 21 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0069

🔁 Trial 9
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00521
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0055 | Train MAE: 0.05 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.002897. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.002842. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.002366. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 4.9s
✅ Mejor val_loss: 0.002193. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.9s
✅ Mejor val_loss: 0.001988. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.001816. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0390 | Train MAE: 0.16 | Val Loss: 0.0457 | Val MAE: 0.19 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0419 | Train MAE: 0.17 | Val Loss: 0.0451 | Val MAE: 0.19 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0420 | Train MAE: 0.17 | Val Loss: 0.0451 | Val MAE: 0.19 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0411 | Train MAE: 0.17 | Val Loss: 0.0447 | Val MAE: 0.18 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0426 | Train MAE: 0.17 | Val Loss: 0.0470 | Val MAE: 0.18 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0470

🔁 Trial 10
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00822
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0085 | Train MAE: 0.07 | Val Loss: 0.0035 | Val MAE: 0.05 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.003546. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0035 | Train MAE: 0.05 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.002376. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.002308. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0026

🔁 Trial 11
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00509
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0071 | Train MAE: 0.06 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002363. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.002282. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.002245. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.002144. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.002110. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.002084. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0033 | Val MAE: 0.05 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0022

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 32
   - num_layers: 3
   - lr: 0.005091589031693267


📍 Parking 78 | 🧠 Modelo: RNN
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0498 | Train MAE: 0.15 | Val Loss: 0.0172 | Val MAE: 0.09 | ⏱️ Time: 3.3s
✅ Mejor val_loss: 0.017185. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0126 | Train MAE: 0.08 | Val Loss: 0.0092 | Val MAE: 0.06 | ⏱️ Time: 3.3s
✅ Mejor val_loss: 0.009221. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0071 | Train MAE: 0.06 | Val Loss: 0.0060 | Val MAE: 0.04 | ⏱️ Time: 3.3s
✅ Mejor val_loss: 0.006040. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0051 | Train MAE: 0.05 | Val Loss: 0.0050 | Val MAE: 0.04 | ⏱️ Time: 3.3s
✅ Mejor val_loss: 0.005006. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0042 | Train MAE: 0.04 | Val Loss: 0.0039 | Val MAE: 0.04 | ⏱️ Time: 3.3s
✅ Mejor val_loss: 0.003948. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0035 | Train MAE: 0.04 | Val Loss: 0.0037 | Val MAE: 0.03 | ⏱️ Time: 3.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0030 | Train MAE: 0.03 | Val Loss: 0.0030 | Val MAE: 0.03 | ⏱️ Time: 3.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0025 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 3.3s
✅ Mejor val_loss: 0.002422. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.02 | ⏱️ Time: 3.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.

🧪 Optimizando RNN con Optuna para parking 78...


🔁 Trial 0
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00545
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0104 | Train MAE: 0.06 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.002200. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0056 | Val MAE: 0.07 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001955. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0036 | Val MAE: 0.05 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001678. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001643. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001534. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001396. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001257. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 20 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0018

🔁 Trial 1
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00764
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0205 | Train MAE: 0.09 | Val Loss: 0.0033 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.003335. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.002391. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001887. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001796. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001747. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001581. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001468. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001452. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001396. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001353. Guardando modelo...

📊 Epoch 23/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 26/30 | Train Loss: 0.0225 | Train MAE: 0.08 | Val Loss: 0.0305 | Val MAE: 0.15 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 27/30 | Train Loss: 0.0314 | Train MAE: 0.13 | Val Loss: 0.0289 | Val MAE: 0.13 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 27 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0289

🔁 Trial 2
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00553
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0222 | Train MAE: 0.10 | Val Loss: 0.0051 | Val MAE: 0.04 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.005071. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0038 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001839. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001632. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001621. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001464. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0015

🔁 Trial 3
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00685
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0093 | Train MAE: 0.06 | Val Loss: 0.0022 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.002178. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.002140. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001580. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001526. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001449. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0015 | Train MAE: 0.02 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0039 | Train MAE: 0.03 | Val Loss: 0.1245 | Val MAE: 0.32 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.1245

🔁 Trial 4
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00555
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0203 | Train MAE: 0.10 | Val Loss: 0.0048 | Val MAE: 0.06 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.004795. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.002034. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001877. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001867. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001834. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001749. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001732. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001704. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001525. Guardando modelo...

📊 Epoch 22/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 26/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 26 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0019

🔁 Trial 5
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00956
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0118 | Train MAE: 0.07 | Val Loss: 0.0041 | Val MAE: 0.03 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.004091. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001858. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001721. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001647. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001488. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001404. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 15 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0016

🔁 Trial 6
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00814
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0123 | Train MAE: 0.07 | Val Loss: 0.0037 | Val MAE: 0.05 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.003682. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001816. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001712. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0188 | Train MAE: 0.07 | Val Loss: 0.0295 | Val MAE: 0.15 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0293 | Train MAE: 0.13 | Val Loss: 0.0332 | Val MAE: 0.16 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0295 | Train MAE: 0.13 | Val Loss: 0.0308 | Val MAE: 0.15 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0308

🔁 Trial 7
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00730
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0136 | Train MAE: 0.08 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.002514. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.002099. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001859. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001809. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001542. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0032

🔁 Trial 8
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00688
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0168 | Train MAE: 0.09 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.002201. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001778. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001609. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001579. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001387. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0016

🔁 Trial 9
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00590
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0105 | Train MAE: 0.07 | Val Loss: 0.0020 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001981. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0036 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001904. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001852. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001741. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001672. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001475. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001427. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001348. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0116 | Train MAE: 0.05 | Val Loss: 0.0442 | Val MAE: 0.12 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0295 | Train MAE: 0.13 | Val Loss: 0.0294 | Val MAE: 0.15 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0296 | Train MAE: 0.13 | Val Loss: 0.0300 | Val MAE: 0.12 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 22 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0300

🔁 Trial 10
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00510
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0295 | Train MAE: 0.12 | Val Loss: 0.0110 | Val MAE: 0.08 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.011049. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0065 | Train MAE: 0.06 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.002431. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0040 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.002284. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0035 | Val MAE: 0.04 | ⏱️ Time: 3.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001793. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0025 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001763. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0025 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001729. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001616. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0022

🔁 Trial 11
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00895
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0524 | Train MAE: 0.16 | Val Loss: 0.0294 | Val MAE: 0.12 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.029412. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0285 | Train MAE: 0.13 | Val Loss: 0.0305 | Val MAE: 0.12 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0286 | Train MAE: 0.13 | Val Loss: 0.0304 | Val MAE: 0.13 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0284 | Train MAE: 0.13 | Val Loss: 0.0294 | Val MAE: 0.13 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.029387. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0284 | Train MAE: 0.13 | Val Loss: 0.0288 | Val MAE: 0.13 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.028800. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0285 | Train MAE: 0.13 | Val Loss: 0.0300 | Val MAE: 0.13 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0286 | Train MAE: 0.13 | Val Loss: 0.0294 | Val MAE: 0.13 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0289 | Train MAE: 0.13 | Val Loss: 0.0291 | Val MAE: 0.13 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0289 | Train MAE: 0.13 | Val Loss: 0.0282 | Val MAE: 0.13 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.028208. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0286 | Train MAE: 0.13 | Val Loss: 0.0295 | Val MAE: 0.15 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0285 | Train MAE: 0.13 | Val Loss: 0.0284 | Val MAE: 0.13 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0288 | Train MAE: 0.13 | Val Loss: 0.0283 | Val MAE: 0.14 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0287 | Train MAE: 0.13 | Val Loss: 0.0304 | Val MAE: 0.12 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0287 | Train MAE: 0.13 | Val Loss: 0.0280 | Val MAE: 0.13 | ⏱️ Time: 3.9s
✅ Mejor val_loss: 0.028047. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0287 | Train MAE: 0.13 | Val Loss: 0.0282 | Val MAE: 0.14 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0287 | Train MAE: 0.13 | Val Loss: 0.0280 | Val MAE: 0.13 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.027954. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0286 | Train MAE: 0.13 | Val Loss: 0.0288 | Val MAE: 0.14 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0286 | Train MAE: 0.13 | Val Loss: 0.0282 | Val MAE: 0.13 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0288 | Train MAE: 0.13 | Val Loss: 0.0298 | Val MAE: 0.14 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0285 | Train MAE: 0.13 | Val Loss: 0.0295 | Val MAE: 0.13 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0287 | Train MAE: 0.13 | Val Loss: 0.0293 | Val MAE: 0.12 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 21 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0293

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 32
   - num_layers: 3
   - lr: 0.00553062583004279





📍 Parking 6 | 🧠 Modelo: LSTM
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0035 | Train MAE: 0.04 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 6.3s
✅ Mejor val_loss: 0.003078. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.2s
✅ Mejor val_loss: 0.002047. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.

🧪 Optimizando LSTM con Optuna para parking 6...


🔁 Trial 0
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00581
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0253 | Train MAE: 0.11 | Val Loss: 0.0045 | Val MAE: 0.05 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.004505. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0036 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002064. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001933. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001870. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001822. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001608. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001527. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0021

🔁 Trial 1
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00898
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0107 | Train MAE: 0.07 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002007. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001941. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001780. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001636. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0020

🔁 Trial 2
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00661
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0227 | Train MAE: 0.10 | Val Loss: 0.0043 | Val MAE: 0.04 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.004295. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0038 | Train MAE: 0.05 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.002203. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.002125. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.002092. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001954. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0025

🔁 Trial 3
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00709
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0178 | Train MAE: 0.09 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.002649. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.002486. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.002102. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001907. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0030 | Val MAE: 0.05 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0030

🔁 Trial 4
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00959
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0127 | Train MAE: 0.08 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.002120. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002007. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001895. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0024

🔁 Trial 5
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00549
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0144 | Train MAE: 0.08 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002044. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001991. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001974. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001903. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001581. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001552. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001409. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 21 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0018

🔁 Trial 6
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00939
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0121 | Train MAE: 0.08 | Val Loss: 0.0032 | Val MAE: 0.05 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.003174. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002014. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0039 | Val MAE: 0.05 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001821. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0019

🔁 Trial 7
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00582
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0253 | Train MAE: 0.11 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.002810. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001875. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001841. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0020

🔁 Trial 8
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00971
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0090 | Train MAE: 0.06 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.002084. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001890. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001698. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001567. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001554. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001513. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001472. Guardando modelo...

📊 Epoch 21/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 25 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0015

🔁 Trial 9
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00663
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0143 | Train MAE: 0.09 | Val Loss: 0.0041 | Val MAE: 0.04 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.004070. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0039 | Train MAE: 0.05 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.002151. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002105. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001734. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0023

🔁 Trial 10
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00805
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0473 | Train MAE: 0.18 | Val Loss: 0.0545 | Val MAE: 0.19 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.054474. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0456 | Train MAE: 0.18 | Val Loss: 0.0545 | Val MAE: 0.20 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0160 | Train MAE: 0.09 | Val Loss: 0.0033 | Val MAE: 0.04 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.003266. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0049 | Train MAE: 0.05 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.002646. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0043 | Train MAE: 0.05 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0040 | Train MAE: 0.05 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.002526. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0037 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0042 | Train MAE: 0.05 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0036 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.002064. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001876. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001857. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001791. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001749. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001704. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001624. Guardando modelo...

📊 Epoch 21/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 25 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0017

🔁 Trial 11
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00820
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0479 | Train MAE: 0.18 | Val Loss: 0.0541 | Val MAE: 0.20 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.054140. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0366 | Train MAE: 0.15 | Val Loss: 0.0073 | Val MAE: 0.07 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.007343. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0077 | Train MAE: 0.07 | Val Loss: 0.0050 | Val MAE: 0.05 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.004953. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0058 | Train MAE: 0.06 | Val Loss: 0.0034 | Val MAE: 0.04 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.003395. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0049 | Train MAE: 0.05 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.003226. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.002788. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0038 | Train MAE: 0.05 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.002148. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.002101. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001829. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001798. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001624. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001542. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 22 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0017

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 64
   - num_layers: 2
   - lr: 0.009706756655432051


📍 Parking 7 | 🧠 Modelo: LSTM
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0352 | Train MAE: 0.13 | Val Loss: 0.0066 | Val MAE: 0.06 | ⏱️ Time: 6.3s
✅ Mejor val_loss: 0.006582. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0049 | Train MAE: 0.05 | Val Loss: 0.0051 | Val MAE: 0.05 | ⏱️ Time: 6.3s
✅ Mejor val_loss: 0.005062. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0037 | Train MAE: 0.04 | Val Loss: 0.0038 | Val MAE: 0.04 | ⏱️ Time: 6.3s
✅ Mejor val_loss: 0.003756. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 6.3s
✅ Mejor val_loss: 0.002667. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.2s
✅ Mejor val_loss: 0.001656. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.

🧪 Optimizando LSTM con Optuna para parking 7...


🔁 Trial 0
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00513
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0131 | Train MAE: 0.08 | Val Loss: 0.0035 | Val MAE: 0.04 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.003494. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0039 | Train MAE: 0.05 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.002178. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001587. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001437. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001419. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001391. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001250. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001203. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001118. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0015

🔁 Trial 1
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00838
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0112 | Train MAE: 0.07 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001870. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001516. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001455. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001389. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001142. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001128. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001039. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000966. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 20 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0013

🔁 Trial 2
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00670
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0082 | Train MAE: 0.06 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001870. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001811. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001563. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001501. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001131. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001090. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001075. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001037. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0015

🔁 Trial 3
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00810
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0070 | Train MAE: 0.05 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001525. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001371. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001272. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001073. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 15 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0012

🔁 Trial 4
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00538
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0091 | Train MAE: 0.06 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001765. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001436. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001327. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001037. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0012

🔁 Trial 5
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00518
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0317 | Train MAE: 0.15 | Val Loss: 0.0220 | Val MAE: 0.10 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.021971. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0084 | Train MAE: 0.07 | Val Loss: 0.0040 | Val MAE: 0.05 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.003963. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0040 | Train MAE: 0.05 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.002101. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.002063. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001811. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001676. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001484. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001196. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001107. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001080. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 20 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0011

🔁 Trial 6
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00538
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0175 | Train MAE: 0.10 | Val Loss: 0.0051 | Val MAE: 0.05 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.005092. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0042 | Train MAE: 0.05 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002454. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001839. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001319. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001167. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001138. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001069. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000967. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0011

🔁 Trial 7
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00986
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0067 | Train MAE: 0.05 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001435. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001333. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001237. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001213. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001110. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001070. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001058. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.000973. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0011

🔁 Trial 8
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00516
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0111 | Train MAE: 0.07 | Val Loss: 0.0036 | Val MAE: 0.05 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.003556. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001748. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001219. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001169. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001150. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.001138. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001005. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 21 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0012

🔁 Trial 9
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00553
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0090 | Train MAE: 0.07 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.002243. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001373. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001316. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001181. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001159. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.000999. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0010

🔁 Trial 10
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00630
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0118 | Train MAE: 0.08 | Val Loss: 0.0036 | Val MAE: 0.05 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.003625. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001487. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001320. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001211. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001097. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0011

🔁 Trial 11
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00601
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0350 | Train MAE: 0.15 | Val Loss: 0.0068 | Val MAE: 0.06 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.006802. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0050 | Train MAE: 0.05 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001774. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001480. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001253. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001087. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001050. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0011

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 16
   - num_layers: 3
   - lr: 0.005525138825449408


📍 Parking 8 | 🧠 Modelo: LSTM
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0160 | Train MAE: 0.09 | Val Loss: 0.0040 | Val MAE: 0.05 | ⏱️ Time: 10.1s
✅ Mejor val_loss: 0.004045. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.3s
✅ Mejor val_loss: 0.001673. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 7 por falta de mejora.

🧪 Optimizando LSTM con Optuna para parking 8...


🔁 Trial 0
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00534
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0120 | Train MAE: 0.07 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.000809. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000749. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.04 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000692. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0011

🔁 Trial 1
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00799
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0251 | Train MAE: 0.11 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.001244. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.04 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000809. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000696. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 11.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000649. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000614. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.03 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0010

🔁 Trial 2
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00687
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0324 | Train MAE: 0.13 | Val Loss: 0.0052 | Val MAE: 0.05 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.005175. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0052 | Train MAE: 0.06 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000930. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000791. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000745. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000678. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0007

🔁 Trial 3
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00632
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0074 | Train MAE: 0.06 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000994. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000924. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000743. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000723. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000635. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 15 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0008

🔁 Trial 4
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00628
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0640 | Train MAE: 0.22 | Val Loss: 0.0233 | Val MAE: 0.13 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.023348. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0328 | Train MAE: 0.14 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.002401. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0048 | Train MAE: 0.05 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.001014. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 11.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.6s
✅ Mejor val_loss: 0.000784. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.7s
✅ Mejor val_loss: 0.000759. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.000666. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0009

🔁 Trial 5
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00659
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0292 | Train MAE: 0.11 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.002917. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.000875. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.000856. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.000780. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.03 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0011

🔁 Trial 6
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00917
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0096 | Train MAE: 0.07 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.001032. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.000766. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.000711. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0012

🔁 Trial 7
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00869
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0482 | Train MAE: 0.17 | Val Loss: 0.0046 | Val MAE: 0.05 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.004591. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0071 | Train MAE: 0.07 | Val Loss: 0.0034 | Val MAE: 0.05 | ⏱️ Time: 11.6s
✅ Mejor val_loss: 0.003428. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0051 | Train MAE: 0.05 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.002432. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0039 | Train MAE: 0.05 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.001449. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.6s
✅ Mejor val_loss: 0.000919. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 11.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.000771. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.000734. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.000704. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 21 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0026

🔁 Trial 8
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00893
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0456 | Train MAE: 0.16 | Val Loss: 0.0041 | Val MAE: 0.05 | ⏱️ Time: 11.7s
✅ Mejor val_loss: 0.004056. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.000901. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.7s
✅ Mejor val_loss: 0.000831. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0014

🔁 Trial 9
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00702
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0736 | Train MAE: 0.23 | Val Loss: 0.0300 | Val MAE: 0.15 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.029957. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0655 | Train MAE: 0.22 | Val Loss: 0.0313 | Val MAE: 0.16 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0419 | Train MAE: 0.16 | Val Loss: 0.0072 | Val MAE: 0.07 | ⏱️ Time: 11.7s
✅ Mejor val_loss: 0.007236. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0116 | Train MAE: 0.08 | Val Loss: 0.0035 | Val MAE: 0.04 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.003490. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0070 | Train MAE: 0.06 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.003239. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0055 | Train MAE: 0.06 | Val Loss: 0.0047 | Val MAE: 0.06 | ⏱️ Time: 11.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0047 | Train MAE: 0.05 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.6s
✅ Mejor val_loss: 0.001802. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0040 | Train MAE: 0.05 | Val Loss: 0.0034 | Val MAE: 0.05 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.001309. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.000936. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.7s
✅ Mejor val_loss: 0.000917. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.6s
✅ Mejor val_loss: 0.000895. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.6s
✅ Mejor val_loss: 0.000852. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 23 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0019

🔁 Trial 10
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00507
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0078 | Train MAE: 0.06 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.000939. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.7s
✅ Mejor val_loss: 0.000768. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.000696. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.000669. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0007

🔁 Trial 11
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00504
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0079 | Train MAE: 0.06 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.000980. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.000924. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.000828. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.000771. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.000719. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.000671. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 10.7s
✅ Mejor val_loss: 0.000648. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.000629. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 19 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0007

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 32
   - num_layers: 2
   - lr: 0.005066299289101385


📍 Parking 13 | 🧠 Modelo: LSTM
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0140 | Train MAE: 0.08 | Val Loss: 0.0061 | Val MAE: 0.05 | ⏱️ Time: 6.2s
✅ Mejor val_loss: 0.006055. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0036 | Train MAE: 0.04 | Val Loss: 0.0030 | Val MAE: 0.03 | ⏱️ Time: 6.2s
✅ Mejor val_loss: 0.002990. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001700. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.

🧪 Optimizando LSTM con Optuna para parking 13...


🔁 Trial 0
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00797
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0223 | Train MAE: 0.11 | Val Loss: 0.0048 | Val MAE: 0.05 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.004770. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0037 | Train MAE: 0.05 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001292. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000876. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000862. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000712. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0007

🔁 Trial 1
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00647
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0071 | Train MAE: 0.05 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001038. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.000808. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.000775. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000710. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000689. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.000642. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000620. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000597. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000567. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0007 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0007 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 23 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0007

🔁 Trial 2
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00963
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0097 | Train MAE: 0.06 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.002060. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001078. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000935. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000808. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000761. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.000680. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 19 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0008

🔁 Trial 3
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00731
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0161 | Train MAE: 0.09 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001381. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001188. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.000953. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.000848. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0012

🔁 Trial 4
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00563
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0266 | Train MAE: 0.12 | Val Loss: 0.0073 | Val MAE: 0.06 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.007333. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001729. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001052. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.000821. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000758. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000732. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.000660. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000641. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000588. Guardando modelo...

📊 Epoch 20/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 24 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0007

🔁 Trial 5
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00926
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0529 | Train MAE: 0.17 | Val Loss: 0.0255 | Val MAE: 0.12 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.025461. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0307 | Train MAE: 0.14 | Val Loss: 0.0295 | Val MAE: 0.13 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0168 | Train MAE: 0.10 | Val Loss: 0.0038 | Val MAE: 0.05 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.003823. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0046 | Train MAE: 0.05 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001427. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0035 | Train MAE: 0.04 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001398. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0010 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001030. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001008. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.3s
✅ Mejor val_loss: 0.000807. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0010

🔁 Trial 6
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00832
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0061 | Train MAE: 0.05 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001185. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001114. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000801. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000741. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000691. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000606. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 15 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0007

🔁 Trial 7
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00828
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0188 | Train MAE: 0.10 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001524. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000953. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000844. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.000811. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.000743. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000707. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000696. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000631. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000596. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 22 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0006

🔁 Trial 8
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00664
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0112 | Train MAE: 0.07 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001588. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000913. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000817. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000774. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.000625. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0006

🔁 Trial 9
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00818
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0440 | Train MAE: 0.16 | Val Loss: 0.0155 | Val MAE: 0.09 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.015455. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0052 | Train MAE: 0.05 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.002126. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001122. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001097. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001027. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000892. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000868. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.000800. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000775. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000700. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 20 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0010

🔁 Trial 10
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00504
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0118 | Train MAE: 0.07 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001544. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.000978. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000870. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000831. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000734. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000677. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.000646. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000600. Guardando modelo...

📊 Epoch 22/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 26/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 26 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0006

🔁 Trial 11
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00514
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0102 | Train MAE: 0.07 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001894. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001006. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.000927. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000917. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.000901. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.000795. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.000738. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000720. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000639. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000622. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000578. Guardando modelo...

📊 Epoch 21/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 25 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0007

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 32
   - num_layers: 2
   - lr: 0.005039859518564822


📍 Parking 34 | 🧠 Modelo: LSTM
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0296 | Train MAE: 0.13 | Val Loss: 0.0070 | Val MAE: 0.06 | ⏱️ Time: 4.2s
✅ Mejor val_loss: 0.006958. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0055 | Train MAE: 0.06 | Val Loss: 0.0059 | Val MAE: 0.06 | ⏱️ Time: 4.2s
✅ Mejor val_loss: 0.005923. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0048 | Train MAE: 0.05 | Val Loss: 0.0050 | Val MAE: 0.05 | ⏱️ Time: 4.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0042 | Val MAE: 0.05 | ⏱️ Time: 4.2s
✅ Mejor val_loss: 0.004219. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 4.2s
✅ Mejor val_loss: 0.002756. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 4.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.2s
✅ Mejor val_loss: 0.001614. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.

🧪 Optimizando LSTM con Optuna para parking 34...


🔁 Trial 0
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00511
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0123 | Train MAE: 0.08 | Val Loss: 0.0043 | Val MAE: 0.05 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.004340. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001609. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001091. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.000978. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.7s
✅ Mejor val_loss: 0.000968. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0012

🔁 Trial 1
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00616
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0398 | Train MAE: 0.17 | Val Loss: 0.0325 | Val MAE: 0.16 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.032507. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0237 | Train MAE: 0.14 | Val Loss: 0.0088 | Val MAE: 0.07 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.008792. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0067 | Train MAE: 0.06 | Val Loss: 0.0036 | Val MAE: 0.04 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.003588. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0036 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.7s
✅ Mejor val_loss: 0.002018. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.001730. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.001565. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.7s
✅ Mejor val_loss: 0.001474. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.001339. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.001166. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0015

🔁 Trial 2
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00510
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0122 | Train MAE: 0.08 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.002977. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.001284. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.001215. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.001040. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.000996. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.000966. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.000895. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0010

🔁 Trial 3
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00592
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0096 | Train MAE: 0.07 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.002347. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001591. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001175. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001146. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001062. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.000994. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.000971. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 20 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0012

🔁 Trial 4
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00597
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0087 | Train MAE: 0.07 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001566. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001061. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.000954. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.000931. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0011

🔁 Trial 5
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00532
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0136 | Train MAE: 0.09 | Val Loss: 0.0039 | Val MAE: 0.04 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.003935. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001240. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001136. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001069. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001025. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.000928. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.000887. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.000836. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 22 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0009

🔁 Trial 6
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00794
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0082 | Train MAE: 0.07 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.002399. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001375. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001080. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.000854. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0010

🔁 Trial 7
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00599
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0119 | Train MAE: 0.08 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.003194. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001808. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001267. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001255. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001165. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.000980. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.000901. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0009

🔁 Trial 8
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00892
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0083 | Train MAE: 0.06 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001575. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001204. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.000963. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0012

🔁 Trial 9
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00800
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0300 | Train MAE: 0.15 | Val Loss: 0.0080 | Val MAE: 0.07 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.008049. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0050 | Train MAE: 0.05 | Val Loss: 0.0033 | Val MAE: 0.05 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.003266. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001471. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001277. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.7s
✅ Mejor val_loss: 0.001182. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001033. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.000923. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 19 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0012

🔁 Trial 10
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00690
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0309 | Train MAE: 0.16 | Val Loss: 0.0326 | Val MAE: 0.17 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.032644. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0286 | Train MAE: 0.15 | Val Loss: 0.0326 | Val MAE: 0.17 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.032607. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0155 | Train MAE: 0.10 | Val Loss: 0.0044 | Val MAE: 0.05 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.004353. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0044 | Train MAE: 0.05 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.002776. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.002223. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.002100. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.001708. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.001499. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.001282. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.001159. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.001067. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.03 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.001009. Guardando modelo...

📊 Epoch 20/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.000977. Guardando modelo...

📊 Epoch 22/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.000955. Guardando modelo...

📊 Epoch 23/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.000916. Guardando modelo...

📊 Epoch 26/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 27/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 28/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 29/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 30/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 30 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0011

🔁 Trial 11
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00558
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0101 | Train MAE: 0.07 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001777. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001287. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001208. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001044. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.000967. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.000889. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.000832. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0009

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 64
   - num_layers: 3
   - lr: 0.005317901682182707


📍 Parking 75 | 🧠 Modelo: LSTM
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0207 | Train MAE: 0.11 | Val Loss: 0.0077 | Val MAE: 0.07 | ⏱️ Time: 10.1s
✅ Mejor val_loss: 0.007685. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0038 | Val MAE: 0.05 | ⏱️ Time: 10.2s
✅ Mejor val_loss: 0.003786. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 10.1s
✅ Mejor val_loss: 0.002487. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.

🧪 Optimizando LSTM con Optuna para parking 75...


🔁 Trial 0
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00545
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0093 | Train MAE: 0.07 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.7s
✅ Mejor val_loss: 0.002556. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.002429. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.002100. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.002018. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.8s
✅ Mejor val_loss: 0.001958. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.001814. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.7s
✅ Mejor val_loss: 0.001795. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.7s
✅ Mejor val_loss: 0.001678. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.001664. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.001596. Guardando modelo...

📊 Epoch 21/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.001553. Guardando modelo...

📊 Epoch 25/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 10.8s
✅ Mejor val_loss: 0.001525. Guardando modelo...

📊 Epoch 26/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 27/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 28/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 29/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 30/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 30 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0017

🔁 Trial 1
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00990
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0078 | Train MAE: 0.06 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.002364. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.002034. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.001991. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.1s
✅ Mejor val_loss: 0.001900. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.001685. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0018

🔁 Trial 2
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00719
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0076 | Train MAE: 0.06 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.002436. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 11.2s
✅ Mejor val_loss: 0.002343. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.002212. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.002022. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.1s
✅ Mejor val_loss: 0.001967. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.1s
✅ Mejor val_loss: 0.001873. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 11.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.1s
✅ Mejor val_loss: 0.001757. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.001629. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 22 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0018

🔁 Trial 3
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00970
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0074 | Train MAE: 0.06 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.002742. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 11.1s
✅ Mejor val_loss: 0.002343. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.002097. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.2s
✅ Mejor val_loss: 0.001961. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.001886. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.001852. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0024

🔁 Trial 4
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00997
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0104 | Train MAE: 0.07 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 11.1s
✅ Mejor val_loss: 0.002394. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 11.1s
✅ Mejor val_loss: 0.002314. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.2s
✅ Mejor val_loss: 0.002074. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 11.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0021

🔁 Trial 5
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00861
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0059 | Train MAE: 0.05 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.002246. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.002128. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.8s
✅ Mejor val_loss: 0.002076. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.8s
✅ Mejor val_loss: 0.001929. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.001750. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.001717. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0019

🔁 Trial 6
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00786
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0097 | Train MAE: 0.07 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.002355. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.8s
✅ Mejor val_loss: 0.002028. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 11.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.002000. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.001853. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.6s
✅ Mejor val_loss: 0.001813. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.6s
✅ Mejor val_loss: 0.001744. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.7s
✅ Mejor val_loss: 0.001692. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 21 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0017

🔁 Trial 7
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00663
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0133 | Train MAE: 0.08 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.002645. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.002369. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.002157. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.002070. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.001817. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0019

🔁 Trial 8
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00566
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0088 | Train MAE: 0.07 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.002440. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0034 | Val MAE: 0.05 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.7s
✅ Mejor val_loss: 0.002106. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0022

🔁 Trial 9
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00524
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0086 | Train MAE: 0.07 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.002418. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.002024. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 11.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.001979. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.001897. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.001764. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0021

🔁 Trial 10
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00608
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0067 | Train MAE: 0.06 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.002381. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.002201. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.001913. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.7s
✅ Mejor val_loss: 0.001833. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0019

🔁 Trial 11
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00778
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0083 | Train MAE: 0.06 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.002499. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 11.7s
✅ Mejor val_loss: 0.002266. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.002150. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.002093. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.002003. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.001968. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.7s
✅ Mejor val_loss: 0.001829. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.6s
✅ Mejor val_loss: 0.001803. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.001739. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 21 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0018

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 32
   - num_layers: 2
   - lr: 0.005451511748561059


📍 Parking 77 | 🧠 Modelo: LSTM
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0377 | Train MAE: 0.15 | Val Loss: 0.0149 | Val MAE: 0.10 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.014944. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0084 | Train MAE: 0.07 | Val Loss: 0.0060 | Val MAE: 0.06 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.006045. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0042 | Train MAE: 0.05 | Val Loss: 0.0039 | Val MAE: 0.05 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.003892. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.002324. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.

🧪 Optimizando LSTM con Optuna para parking 77...


🔁 Trial 0
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00509
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0434 | Train MAE: 0.16 | Val Loss: 0.0070 | Val MAE: 0.07 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.006990. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0057 | Train MAE: 0.06 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.002758. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0038 | Train MAE: 0.05 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.002404. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.002206. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001860. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.001740. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.001672. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001437. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0016

🔁 Trial 1
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00510
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0146 | Train MAE: 0.09 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002515. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002176. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001885. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001854. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001806. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001795. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001597. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0016

🔁 Trial 2
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00696
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0237 | Train MAE: 0.11 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002872. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0036 | Train MAE: 0.05 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002162. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002045. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001765. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001595. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0017

🔁 Trial 3
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00552
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0120 | Train MAE: 0.08 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002142. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.002026. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001878. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001799. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0026

🔁 Trial 4
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00563
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0422 | Train MAE: 0.17 | Val Loss: 0.0436 | Val MAE: 0.19 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.043606. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0099 | Train MAE: 0.08 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.003081. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.002211. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.002135. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.001932. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.001746. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.001650. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0021 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.001613. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.04 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0019

🔁 Trial 5
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00593
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0080 | Train MAE: 0.06 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.002097. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.001951. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0021 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.001936. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.001821. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001567. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001448. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0015

🔁 Trial 6
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00982
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0137 | Train MAE: 0.08 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002079. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0032 | Val MAE: 0.05 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001938. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001703. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.001624. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.001507. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001418. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001314. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 23 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0014

🔁 Trial 7
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00618
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0080 | Train MAE: 0.06 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002609. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001993. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001864. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001582. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001526. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.001448. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.001384. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 20 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0019

🔁 Trial 8
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00853
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0113 | Train MAE: 0.07 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.002053. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.001910. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.001855. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.001628. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.001556. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.001408. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 15 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0016

🔁 Trial 9
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00804
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0185 | Train MAE: 0.10 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.002553. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002489. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.002157. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.001989. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.001924. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.001801. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.001665. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001642. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.001629. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.001595. Guardando modelo...

📊 Epoch 20/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001557. Guardando modelo...

📊 Epoch 21/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.001463. Guardando modelo...

📊 Epoch 22/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.001381. Guardando modelo...

📊 Epoch 26/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 27/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 28/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 29/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 30/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 30 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0014

🔁 Trial 10
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00996
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0065 | Train MAE: 0.06 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.002934. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.002654. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.001867. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.001574. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.001458. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.001432. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.001394. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0015

🔁 Trial 11
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00858
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0131 | Train MAE: 0.08 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.002192. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.002030. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.001937. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.001847. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.1s
✅ Mejor val_loss: 0.001822. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.001670. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.0s
✅ Mejor val_loss: 0.001465. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 21 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0015

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 64
   - num_layers: 3
   - lr: 0.0098193899958898


📍 Parking 78 | 🧠 Modelo: LSTM
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0581 | Train MAE: 0.16 | Val Loss: 0.0193 | Val MAE: 0.10 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.019318. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0159 | Train MAE: 0.09 | Val Loss: 0.0123 | Val MAE: 0.07 | ⏱️ Time: 3.3s
✅ Mejor val_loss: 0.012277. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0108 | Train MAE: 0.07 | Val Loss: 0.0101 | Val MAE: 0.07 | ⏱️ Time: 3.3s
✅ Mejor val_loss: 0.010078. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0088 | Train MAE: 0.07 | Val Loss: 0.0078 | Val MAE: 0.06 | ⏱️ Time: 3.3s
✅ Mejor val_loss: 0.007806. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0069 | Train MAE: 0.06 | Val Loss: 0.0060 | Val MAE: 0.05 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.005972. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0048 | Train MAE: 0.05 | Val Loss: 0.0038 | Val MAE: 0.04 | ⏱️ Time: 3.3s
✅ Mejor val_loss: 0.003828. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0033 | Val MAE: 0.04 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0027 | Train MAE: 0.03 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 3.3s
✅ Mejor val_loss: 0.002786. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 3.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 3.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0018 | Train MAE: 0.02 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 3.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.02 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.

🧪 Optimizando LSTM con Optuna para parking 78...


🔁 Trial 0
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00511
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0268 | Train MAE: 0.12 | Val Loss: 0.0082 | Val MAE: 0.06 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.008162. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0052 | Train MAE: 0.05 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.002303. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001581. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001519. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001358. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001324. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0015 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001242. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001152. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001120. Guardando modelo...

📊 Epoch 20/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 24 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0014

🔁 Trial 1
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00712
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0282 | Train MAE: 0.12 | Val Loss: 0.0063 | Val MAE: 0.05 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.006332. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0046 | Train MAE: 0.05 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.002258. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001551. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001389. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001324. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0021

🔁 Trial 2
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00527
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0302 | Train MAE: 0.12 | Val Loss: 0.0088 | Val MAE: 0.06 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.008836. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0055 | Train MAE: 0.05 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.002261. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001828. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001776. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001536. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001492. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001322. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001275. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0015 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0015

🔁 Trial 3
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00655
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0426 | Train MAE: 0.15 | Val Loss: 0.0285 | Val MAE: 0.13 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.028518. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0285 | Train MAE: 0.13 | Val Loss: 0.0290 | Val MAE: 0.13 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0284 | Train MAE: 0.13 | Val Loss: 0.0293 | Val MAE: 0.13 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0284 | Train MAE: 0.13 | Val Loss: 0.0282 | Val MAE: 0.14 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.028217. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0281 | Train MAE: 0.13 | Val Loss: 0.0282 | Val MAE: 0.13 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.028180. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0189 | Train MAE: 0.10 | Val Loss: 0.0136 | Val MAE: 0.07 | ⏱️ Time: 3.9s
✅ Mejor val_loss: 0.013642. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0099 | Train MAE: 0.07 | Val Loss: 0.0049 | Val MAE: 0.04 | ⏱️ Time: 3.9s
✅ Mejor val_loss: 0.004930. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0073 | Train MAE: 0.06 | Val Loss: 0.0060 | Val MAE: 0.04 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0065 | Train MAE: 0.05 | Val Loss: 0.0035 | Val MAE: 0.03 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.003549. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0060 | Train MAE: 0.05 | Val Loss: 0.0036 | Val MAE: 0.04 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0052 | Train MAE: 0.05 | Val Loss: 0.0036 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0050 | Train MAE: 0.05 | Val Loss: 0.0030 | Val MAE: 0.03 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.003003. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0043 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 3.9s
✅ Mejor val_loss: 0.002362. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0040 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.002104. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0040 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0038 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001956. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0037 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.02 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001754. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 22 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0022

🔁 Trial 4
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00662
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0374 | Train MAE: 0.14 | Val Loss: 0.0280 | Val MAE: 0.13 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.028048. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0287 | Train MAE: 0.13 | Val Loss: 0.0283 | Val MAE: 0.14 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0285 | Train MAE: 0.13 | Val Loss: 0.0282 | Val MAE: 0.13 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0161 | Train MAE: 0.09 | Val Loss: 0.0075 | Val MAE: 0.08 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.007533. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0060 | Train MAE: 0.05 | Val Loss: 0.0044 | Val MAE: 0.05 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.004447. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0047 | Train MAE: 0.05 | Val Loss: 0.0036 | Val MAE: 0.04 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.003585. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.002182. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.002116. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0025 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001427. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001388. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001253. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 19 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0018

🔁 Trial 5
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00720
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0268 | Train MAE: 0.11 | Val Loss: 0.0041 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.004092. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001721. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001649. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001441. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001429. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001327. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001280. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001201. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001180. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001096. Guardando modelo...

📊 Epoch 20/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 24 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0011

🔁 Trial 6
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00818
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0315 | Train MAE: 0.13 | Val Loss: 0.0284 | Val MAE: 0.13 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.028369. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0285 | Train MAE: 0.13 | Val Loss: 0.0292 | Val MAE: 0.12 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0286 | Train MAE: 0.13 | Val Loss: 0.0297 | Val MAE: 0.15 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0127 | Train MAE: 0.08 | Val Loss: 0.0035 | Val MAE: 0.03 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.003459. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0041 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.002525. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001738. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0026 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001692. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.9s
✅ Mejor val_loss: 0.001486. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 3.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001379. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001172. Guardando modelo...

📊 Epoch 20/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.04 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 24 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0014

🔁 Trial 7
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00863
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0627 | Train MAE: 0.17 | Val Loss: 0.0281 | Val MAE: 0.13 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.028138. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0286 | Train MAE: 0.13 | Val Loss: 0.0288 | Val MAE: 0.13 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0285 | Train MAE: 0.13 | Val Loss: 0.0294 | Val MAE: 0.14 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0284 | Train MAE: 0.13 | Val Loss: 0.0289 | Val MAE: 0.14 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0286 | Train MAE: 0.13 | Val Loss: 0.0285 | Val MAE: 0.13 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0284 | Train MAE: 0.13 | Val Loss: 0.0281 | Val MAE: 0.13 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.028056. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0284 | Train MAE: 0.13 | Val Loss: 0.0313 | Val MAE: 0.12 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0285 | Train MAE: 0.13 | Val Loss: 0.0285 | Val MAE: 0.13 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0284 | Train MAE: 0.13 | Val Loss: 0.0280 | Val MAE: 0.13 | ⏱️ Time: 4.0s
✅ Mejor val_loss: 0.027979. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0284 | Train MAE: 0.13 | Val Loss: 0.0281 | Val MAE: 0.13 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0283 | Train MAE: 0.13 | Val Loss: 0.0300 | Val MAE: 0.14 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0285 | Train MAE: 0.13 | Val Loss: 0.0300 | Val MAE: 0.13 | ⏱️ Time: 3.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0285 | Train MAE: 0.13 | Val Loss: 0.0284 | Val MAE: 0.13 | ⏱️ Time: 3.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0284 | Train MAE: 0.13 | Val Loss: 0.0286 | Val MAE: 0.13 | ⏱️ Time: 3.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0286

🔁 Trial 8
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00582
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0858 | Train MAE: 0.20 | Val Loss: 0.0297 | Val MAE: 0.13 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.029670. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0291 | Train MAE: 0.13 | Val Loss: 0.0279 | Val MAE: 0.13 | ⏱️ Time: 3.9s
✅ Mejor val_loss: 0.027914. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0284 | Train MAE: 0.13 | Val Loss: 0.0294 | Val MAE: 0.13 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0284 | Train MAE: 0.13 | Val Loss: 0.0280 | Val MAE: 0.14 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0275 | Train MAE: 0.13 | Val Loss: 0.0213 | Val MAE: 0.09 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.021314. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0166 | Train MAE: 0.09 | Val Loss: 0.0097 | Val MAE: 0.07 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.009655. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0114 | Train MAE: 0.07 | Val Loss: 0.0050 | Val MAE: 0.06 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.004980. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0080 | Train MAE: 0.06 | Val Loss: 0.0048 | Val MAE: 0.04 | ⏱️ Time: 3.9s
✅ Mejor val_loss: 0.004783. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0059 | Train MAE: 0.05 | Val Loss: 0.0027 | Val MAE: 0.03 | ⏱️ Time: 3.9s
✅ Mejor val_loss: 0.002663. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0050 | Train MAE: 0.05 | Val Loss: 0.0036 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0046 | Train MAE: 0.05 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.002245. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0043 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0042 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.002108. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0040 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001898. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0040 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 3.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0037 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0035 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.9s
✅ Mejor val_loss: 0.001689. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.02 | ⏱️ Time: 4.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0055 | Val MAE: 0.04 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 23 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0020

🔁 Trial 9
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00906
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0242 | Train MAE: 0.11 | Val Loss: 0.0114 | Val MAE: 0.07 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.011376. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0081 | Train MAE: 0.06 | Val Loss: 0.0031 | Val MAE: 0.03 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.003119. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001735. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001563. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001501. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001462. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001425. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001372. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001342. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001296. Guardando modelo...

📊 Epoch 20/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 24 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0014

🔁 Trial 10
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00984
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0155 | Train MAE: 0.08 | Val Loss: 0.0026 | Val MAE: 0.03 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.002567. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0026 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001515. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001344. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001161. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0018 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 15 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0018

🔁 Trial 11
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00789
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0258 | Train MAE: 0.11 | Val Loss: 0.0117 | Val MAE: 0.08 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.011691. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0050 | Train MAE: 0.05 | Val Loss: 0.0026 | Val MAE: 0.03 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.002644. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001665. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001540. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001513. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001438. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001246. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0014

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 32
   - num_layers: 2
   - lr: 0.007198613599000658





📍 Parking 6 | 🧠 Modelo: GRU
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0299 | Train MAE: 0.12 | Val Loss: 0.0098 | Val MAE: 0.07 | ⏱️ Time: 6.2s
✅ Mejor val_loss: 0.009836. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0062 | Train MAE: 0.06 | Val Loss: 0.0052 | Val MAE: 0.05 | ⏱️ Time: 6.2s
✅ Mejor val_loss: 0.005192. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0037 | Train MAE: 0.04 | Val Loss: 0.0036 | Val MAE: 0.05 | ⏱️ Time: 6.2s
✅ Mejor val_loss: 0.003594. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 6.2s
✅ Mejor val_loss: 0.002534. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.

🧪 Optimizando GRU con Optuna para parking 6...


🔁 Trial 0
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00939
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0099 | Train MAE: 0.07 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.002527. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.002194. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0029 | Val MAE: 0.05 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001973. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001733. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001718. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001625. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001605. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001508. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 23 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0017

🔁 Trial 1
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00531
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0102 | Train MAE: 0.07 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.002396. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001978. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001799. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001722. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001686. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001620. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001585. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001551. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001470. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 22 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0015

🔁 Trial 2
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00561
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0106 | Train MAE: 0.06 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.002460. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.002036. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001826. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001742. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001614. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001549. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001447. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0017

🔁 Trial 3
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00882
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0115 | Train MAE: 0.07 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.002648. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.002106. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001602. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001526. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 15 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0016

🔁 Trial 4
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00578
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0386 | Train MAE: 0.15 | Val Loss: 0.0242 | Val MAE: 0.11 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.024174. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0221 | Train MAE: 0.11 | Val Loss: 0.0249 | Val MAE: 0.12 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0217 | Train MAE: 0.11 | Val Loss: 0.0237 | Val MAE: 0.12 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.023677. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0217 | Train MAE: 0.11 | Val Loss: 0.0232 | Val MAE: 0.11 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.023223. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0215 | Train MAE: 0.11 | Val Loss: 0.0236 | Val MAE: 0.12 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0214 | Train MAE: 0.11 | Val Loss: 0.0238 | Val MAE: 0.12 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0212 | Train MAE: 0.11 | Val Loss: 0.0233 | Val MAE: 0.11 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0210 | Train MAE: 0.10 | Val Loss: 0.0235 | Val MAE: 0.12 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0208 | Train MAE: 0.10 | Val Loss: 0.0235 | Val MAE: 0.11 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0235

🔁 Trial 5
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00503
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0122 | Train MAE: 0.07 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.002641. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0031 | Val MAE: 0.05 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.002294. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001976. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001914. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001791. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001669. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001640. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001623. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001597. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001577. Guardando modelo...

📊 Epoch 21/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001551. Guardando modelo...

📊 Epoch 22/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001512. Guardando modelo...

📊 Epoch 25/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001439. Guardando modelo...

📊 Epoch 26/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 27/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001360. Guardando modelo...

📊 Epoch 28/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 29/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 30/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora
🎯 Resultado trial 5 → val_loss = 0.0019

🔁 Trial 6
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00585
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0106 | Train MAE: 0.07 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.002311. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001967. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001939. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001731. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001706. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001578. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001471. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 20 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0018

🔁 Trial 7
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00750
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0466 | Train MAE: 0.16 | Val Loss: 0.0255 | Val MAE: 0.12 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.025508. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0220 | Train MAE: 0.11 | Val Loss: 0.0237 | Val MAE: 0.12 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.023655. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0218 | Train MAE: 0.11 | Val Loss: 0.0243 | Val MAE: 0.12 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0215 | Train MAE: 0.11 | Val Loss: 0.0226 | Val MAE: 0.11 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.022627. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0113 | Train MAE: 0.08 | Val Loss: 0.0044 | Val MAE: 0.05 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.004440. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0055 | Train MAE: 0.05 | Val Loss: 0.0034 | Val MAE: 0.04 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.003369. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0046 | Train MAE: 0.05 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.002319. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0039 | Train MAE: 0.05 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001920. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0037 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0035 | Train MAE: 0.04 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001902. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001866. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001785. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 23 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0020

🔁 Trial 8
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00535
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0079 | Train MAE: 0.06 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.003188. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002064. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001805. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001757. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001647. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001486. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0020

🔁 Trial 9
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00760
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0075 | Train MAE: 0.06 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.002222. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001858. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001672. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001471. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001369. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0030 | Val MAE: 0.05 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0015

🔁 Trial 10
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00653
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0086 | Train MAE: 0.06 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.003096. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.002046. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001862. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001687. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0018

🔁 Trial 11
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00743
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0126 | Train MAE: 0.07 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002299. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002213. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002062. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001836. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001783. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001658. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001550. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0032 | Val MAE: 0.05 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 15 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0017

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 64
   - num_layers: 4
   - lr: 0.005311393661479357


📍 Parking 7 | 🧠 Modelo: GRU
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0125 | Train MAE: 0.08 | Val Loss: 0.0039 | Val MAE: 0.04 | ⏱️ Time: 6.2s
✅ Mejor val_loss: 0.003876. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 6.2s
✅ Mejor val_loss: 0.002381. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.2s
✅ Mejor val_loss: 0.001371. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.

🧪 Optimizando GRU con Optuna para parking 7...


🔁 Trial 0
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00930
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0055 | Train MAE: 0.05 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.002235. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001293. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001176. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001059. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001036. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.000927. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 20 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0012

🔁 Trial 1
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00831
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0068 | Train MAE: 0.06 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001741. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001507. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001342. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001188. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0023

🔁 Trial 2
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00684
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0191 | Train MAE: 0.09 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.002475. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001503. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001469. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001261. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001175. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0016

🔁 Trial 3
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00617
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0293 | Train MAE: 0.14 | Val Loss: 0.0170 | Val MAE: 0.09 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.016994. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0158 | Train MAE: 0.09 | Val Loss: 0.0168 | Val MAE: 0.09 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.016781. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0155 | Train MAE: 0.09 | Val Loss: 0.0166 | Val MAE: 0.09 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.016558. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0154 | Train MAE: 0.09 | Val Loss: 0.0182 | Val MAE: 0.09 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0155 | Train MAE: 0.09 | Val Loss: 0.0163 | Val MAE: 0.09 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.016308. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0153 | Train MAE: 0.09 | Val Loss: 0.0168 | Val MAE: 0.09 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0152 | Train MAE: 0.09 | Val Loss: 0.0157 | Val MAE: 0.08 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.015742. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0069 | Train MAE: 0.06 | Val Loss: 0.0036 | Val MAE: 0.05 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.003635. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.001826. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001746. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001617. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001547. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001354. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 21 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0015

🔁 Trial 4
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00776
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0075 | Train MAE: 0.06 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001674. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001395. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001343. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001332. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001208. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001162. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 15 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0013

🔁 Trial 5
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00686
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0233 | Train MAE: 0.09 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.002537. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001935. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001553. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001204. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001184. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001008. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0011

🔁 Trial 6
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00817
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0065 | Train MAE: 0.05 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.002292. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001321. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001130. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001025. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0011

🔁 Trial 7
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00791
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0071 | Train MAE: 0.06 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 7.2s
✅ Mejor val_loss: 0.002092. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001699. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001521. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001268. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001228. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0013

🔁 Trial 8
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00620
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0069 | Train MAE: 0.06 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001558. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001318. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001143. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0013

🔁 Trial 9
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00857
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0071 | Train MAE: 0.06 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001642. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001631. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001328. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.001305. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001166. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0015

🔁 Trial 10
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00501
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0056 | Train MAE: 0.05 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001681. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001447. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001356. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001218. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001180. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001022. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001009. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.000998. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0012

🔁 Trial 11
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00689
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0075 | Train MAE: 0.05 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001738. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001380. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001274. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001113. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0014

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 32
   - num_layers: 3
   - lr: 0.006856469742200535


📍 Parking 8 | 🧠 Modelo: GRU
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0101 | Train MAE: 0.06 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.1s
✅ Mejor val_loss: 0.001947. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.2s
✅ Mejor val_loss: 0.000860. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.

🧪 Optimizando GRU con Optuna para parking 8...


🔁 Trial 0
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00895
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0038 | Train MAE: 0.04 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.000859. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000826. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.2s
✅ Mejor val_loss: 0.000813. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000749. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000739. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.1s
✅ Mejor val_loss: 0.000684. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.000651. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.000605. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 19 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0006

🔁 Trial 1
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00548
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0102 | Train MAE: 0.06 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 11.1s
✅ Mejor val_loss: 0.001433. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.000718. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.000704. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.03 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0010

🔁 Trial 2
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00912
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0059 | Train MAE: 0.05 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.001119. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000731. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.04 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 7 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0017

🔁 Trial 3
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00998
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0054 | Train MAE: 0.05 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 11.6s
✅ Mejor val_loss: 0.001536. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.000776. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.000675. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0010

🔁 Trial 4
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00705
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0062 | Train MAE: 0.05 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.000734. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 6 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0012

🔁 Trial 5
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00856
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0048 | Train MAE: 0.05 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.002205. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.000694. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 7 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0009

🔁 Trial 6
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00948
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0051 | Train MAE: 0.04 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.000815. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.000736. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.000722. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.000675. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.000661. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.000614. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 21 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0009

🔁 Trial 7
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00923
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0483 | Train MAE: 0.16 | Val Loss: 0.0068 | Val MAE: 0.06 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.006827. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0106 | Train MAE: 0.08 | Val Loss: 0.0042 | Val MAE: 0.05 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.004203. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0059 | Train MAE: 0.06 | Val Loss: 0.0019 | Val MAE: 0.04 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.001926. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0038 | Train MAE: 0.05 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.000883. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.000788. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0039 | Val MAE: 0.06 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0017

🔁 Trial 8
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00941
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0041 | Train MAE: 0.04 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.001472. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.001311. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.000789. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.000740. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.000649. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0008

🔁 Trial 9
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00896
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0050 | Train MAE: 0.05 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.000926. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.000796. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.000745. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.000715. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.000680. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0008

🔁 Trial 10
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00745
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0037 | Train MAE: 0.04 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000853. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000762. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000720. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000693. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.000661. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0007

🔁 Trial 11
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00759
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0055 | Train MAE: 0.05 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.000767. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.000652. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0007

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 64
   - num_layers: 3
   - lr: 0.008950569750498152


📍 Parking 13 | 🧠 Modelo: GRU
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0157 | Train MAE: 0.08 | Val Loss: 0.0040 | Val MAE: 0.04 | ⏱️ Time: 6.3s
✅ Mejor val_loss: 0.004021. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0026 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 6.3s
✅ Mejor val_loss: 0.002281. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.2s
✅ Mejor val_loss: 0.001221. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.

🧪 Optimizando GRU con Optuna para parking 13...


🔁 Trial 0
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00772
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0379 | Train MAE: 0.15 | Val Loss: 0.0263 | Val MAE: 0.12 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.026267. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0141 | Train MAE: 0.09 | Val Loss: 0.0040 | Val MAE: 0.05 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.003974. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.002033. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001381. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.001215. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.000872. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.000843. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.000772. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.000759. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.000723. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 23 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0007

🔁 Trial 1
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00676
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0058 | Train MAE: 0.05 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.000920. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.000811. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.000676. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.000618. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0007

🔁 Trial 2
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00834
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0051 | Train MAE: 0.04 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.001103. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000990. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000874. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000713. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.000702. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.000648. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0009

🔁 Trial 3
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00550
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0052 | Train MAE: 0.05 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001596. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000992. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000842. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000770. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000685. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0007

🔁 Trial 4
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00545
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0103 | Train MAE: 0.07 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001971. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000904. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000789. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000749. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.000731. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.000679. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.000667. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0007

🔁 Trial 5
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00521
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0087 | Train MAE: 0.06 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 7.1s
✅ Mejor val_loss: 0.000984. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.000819. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.0s
✅ Mejor val_loss: 0.000760. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 7.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0009

🔁 Trial 6
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00698
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0054 | Train MAE: 0.05 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001279. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000941. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000903. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000859. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000795. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.000719. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000673. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0007

🔁 Trial 7
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00846
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0079 | Train MAE: 0.05 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.001640. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.000817. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.000747. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000653. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000628. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000603. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.03 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 20 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0009

🔁 Trial 8
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00583
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0090 | Train MAE: 0.06 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 6.9s
✅ Mejor val_loss: 0.001610. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.000966. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.000933. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.000905. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.000832. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
✅ Mejor val_loss: 0.000801. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.7s
✅ Mejor val_loss: 0.000746. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 6.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 15 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0011

🔁 Trial 9
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00724
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0039 | Train MAE: 0.04 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001213. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001059. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000757. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000742. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000698. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000595. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0005 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000524. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0007 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0007 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0007 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0007 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 23 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0006

🔁 Trial 10
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00971
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0049 | Train MAE: 0.04 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.001166. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.001069. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000741. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000676. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0007

🔁 Trial 11
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00972
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0047 | Train MAE: 0.04 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.001254. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.000910. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000767. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000750. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000644. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.4s
✅ Mejor val_loss: 0.000632. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.6s
✅ Mejor val_loss: 0.000611. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
✅ Mejor val_loss: 0.000552. Guardando modelo...

📊 Epoch 22/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0007 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0008 | Train MAE: 0.02 | Val Loss: 0.0007 | Val MAE: 0.02 | ⏱️ Time: 6.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0007 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 26/30 | Train Loss: 0.0007 | Train MAE: 0.02 | Val Loss: 0.0006 | Val MAE: 0.02 | ⏱️ Time: 6.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 26 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0006

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 32
   - num_layers: 2
   - lr: 0.00971963275787215


📍 Parking 34 | 🧠 Modelo: GRU
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0149 | Train MAE: 0.09 | Val Loss: 0.0057 | Val MAE: 0.06 | ⏱️ Time: 4.2s
✅ Mejor val_loss: 0.005696. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0039 | Train MAE: 0.05 | Val Loss: 0.0038 | Val MAE: 0.04 | ⏱️ Time: 4.2s
✅ Mejor val_loss: 0.003820. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 4.2s
✅ Mejor val_loss: 0.002710. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.1s
✅ Mejor val_loss: 0.001600. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.

🧪 Optimizando GRU con Optuna para parking 34...


🔁 Trial 0
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00913
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0052 | Train MAE: 0.05 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001432. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001173. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.000917. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.000811. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0010

🔁 Trial 1
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00695
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0088 | Train MAE: 0.07 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 4.7s
✅ Mejor val_loss: 0.002160. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.7s
✅ Mejor val_loss: 0.001252. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.7s
✅ Mejor val_loss: 0.001095. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.7s
✅ Mejor val_loss: 0.000991. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.7s
✅ Mejor val_loss: 0.000928. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0011

🔁 Trial 2
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00593
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0054 | Train MAE: 0.05 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.7s
✅ Mejor val_loss: 0.001440. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001270. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001107. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001047. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.000991. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.000946. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.000906. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0009

🔁 Trial 3
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00820
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0055 | Train MAE: 0.05 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001728. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001477. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001165. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001132. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.000992. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.000867. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0015

🔁 Trial 4
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00903
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0088 | Train MAE: 0.07 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.7s
✅ Mejor val_loss: 0.001855. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.7s
✅ Mejor val_loss: 0.001556. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.7s
✅ Mejor val_loss: 0.001462. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.7s
✅ Mejor val_loss: 0.001225. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0014

🔁 Trial 5
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00574
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0072 | Train MAE: 0.06 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001755. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001539. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001109. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.000976. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.000908. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0010

🔁 Trial 6
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00507
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0099 | Train MAE: 0.08 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.002228. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001601. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001554. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001339. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001240. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001193. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001039. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0012

🔁 Trial 7
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00665
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0496 | Train MAE: 0.17 | Val Loss: 0.0315 | Val MAE: 0.16 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.031490. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0134 | Train MAE: 0.09 | Val Loss: 0.0046 | Val MAE: 0.05 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.004640. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0045 | Train MAE: 0.05 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.002330. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.002207. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.002020. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001858. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001533. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001297. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001156. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0012

🔁 Trial 8
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00585
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0089 | Train MAE: 0.06 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.002024. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001433. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001281. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001145. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001127. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001002. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.000951. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.000934. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.000915. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0008 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.000834. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0010

🔁 Trial 9
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00994
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0053 | Train MAE: 0.05 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.002143. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 4.6s
✅ Mejor val_loss: 0.001394. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001345. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001276. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001096. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.000886. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0009

🔁 Trial 10
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00987
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0049 | Train MAE: 0.05 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001822. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001287. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001198. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0012 | Train MAE: 0.03 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001015. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.000886. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0010

🔁 Trial 11
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00776
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0046 | Train MAE: 0.05 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.5s
✅ Mejor val_loss: 0.001548. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001520. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.001151. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.001054. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.000947. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.03 | ⏱️ Time: 4.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.3s
✅ Mejor val_loss: 0.000933. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0010 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0009 | Val MAE: 0.02 | ⏱️ Time: 4.4s
✅ Mejor val_loss: 0.000868. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0009 | Train MAE: 0.02 | Val Loss: 0.0010 | Val MAE: 0.02 | ⏱️ Time: 4.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0010

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 32
   - num_layers: 2
   - lr: 0.009944171737842306


📍 Parking 75 | 🧠 Modelo: GRU
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0152 | Train MAE: 0.09 | Val Loss: 0.0050 | Val MAE: 0.06 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.004986. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0035 | Val MAE: 0.04 | ⏱️ Time: 10.1s
✅ Mejor val_loss: 0.003491. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 10.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 10.1s
✅ Mejor val_loss: 0.002403. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 10.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.1s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.

🧪 Optimizando GRU con Optuna para parking 75...


🔁 Trial 0
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00687
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0063 | Train MAE: 0.06 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.002459. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.002431. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.002378. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.002230. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.001916. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.001874. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.001797. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.001711. Guardando modelo...

📊 Epoch 22/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.001691. Guardando modelo...

📊 Epoch 26/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 27/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 28/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 29/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 30/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.001643. Guardando modelo...
🎯 Resultado trial 0 → val_loss = 0.0016

🔁 Trial 1
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00726
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0053 | Train MAE: 0.05 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 10.7s
✅ Mejor val_loss: 0.002828. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.002340. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.002012. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.001924. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.001851. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.8s
✅ Mejor val_loss: 0.001776. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.001755. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.001706. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.001668. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.001546. Guardando modelo...

📊 Epoch 20/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 24 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0016

🔁 Trial 2
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00713
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0441 | Train MAE: 0.18 | Val Loss: 0.0211 | Val MAE: 0.11 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.021071. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0215 | Train MAE: 0.11 | Val Loss: 0.0201 | Val MAE: 0.10 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.020131. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0206 | Train MAE: 0.11 | Val Loss: 0.0186 | Val MAE: 0.10 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.018600. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0106 | Train MAE: 0.08 | Val Loss: 0.0044 | Val MAE: 0.05 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.004447. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0064 | Train MAE: 0.06 | Val Loss: 0.0034 | Val MAE: 0.04 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.003376. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0049 | Train MAE: 0.05 | Val Loss: 0.0042 | Val MAE: 0.05 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0046 | Train MAE: 0.05 | Val Loss: 0.0049 | Val MAE: 0.05 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0044 | Train MAE: 0.05 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.002898. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0039 | Train MAE: 0.05 | Val Loss: 0.0040 | Val MAE: 0.05 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0036 | Train MAE: 0.05 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.002814. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0035 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.002645. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0035 | Train MAE: 0.04 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0044 | Val MAE: 0.05 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.002506. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.002377. Guardando modelo...

📊 Epoch 21/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 25 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0030

🔁 Trial 3
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00535
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0067 | Train MAE: 0.06 | Val Loss: 0.0030 | Val MAE: 0.04 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.003048. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.002899. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.002246. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.001900. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.001883. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.001830. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.001638. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 19 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0018

🔁 Trial 4
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00677
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0059 | Train MAE: 0.05 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.002512. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.002372. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.002239. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 11.6s
✅ Mejor val_loss: 0.002150. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.001943. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.001931. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.001802. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.001635. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0018

🔁 Trial 5
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00558
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0090 | Train MAE: 0.06 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.002618. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.002215. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.002100. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.001923. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.001815. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.001770. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.001760. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.001663. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.001582. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 23 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0017

🔁 Trial 6
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00738
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0109 | Train MAE: 0.07 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.002764. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.002567. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.002306. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.002210. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.002126. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.002043. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.001957. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.001871. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.001833. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.001801. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.001713. Guardando modelo...

📊 Epoch 20/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 24 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0018

🔁 Trial 7
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00646
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0103 | Train MAE: 0.08 | Val Loss: 0.0047 | Val MAE: 0.06 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.004714. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0041 | Train MAE: 0.05 | Val Loss: 0.0038 | Val MAE: 0.05 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.003820. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0036 | Train MAE: 0.05 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.002843. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0042 | Val MAE: 0.05 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.002683. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.002278. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 11.3s
✅ Mejor val_loss: 0.002231. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.002208. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.002096. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.002057. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.001947. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 23 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0020

🔁 Trial 8
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00590
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0145 | Train MAE: 0.08 | Val Loss: 0.0029 | Val MAE: 0.04 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.002932. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0035 | Train MAE: 0.05 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 11.6s
✅ Mejor val_loss: 0.002542. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.002454. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.002249. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 11.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0035 | Val MAE: 0.05 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.5s
✅ Mejor val_loss: 0.002101. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.4s
✅ Mejor val_loss: 0.001966. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 11.3s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 15 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0021

🔁 Trial 9
   🔧 Params → hidden_size: 64, num_layers: 2, lr: 0.00691
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0055 | Train MAE: 0.05 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.002781. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.002557. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.5s
✅ Mejor val_loss: 0.002113. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.001965. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 10.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.6s
✅ Mejor val_loss: 0.001932. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.4s
✅ Mejor val_loss: 0.001690. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0020

🔁 Trial 10
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00902
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0078 | Train MAE: 0.06 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.002287. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 11.1s
✅ Mejor val_loss: 0.002219. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.002143. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.0s
✅ Mejor val_loss: 0.002022. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0032 | Val MAE: 0.04 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0021

🔁 Trial 11
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00850
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0061 | Train MAE: 0.05 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 11.1s
✅ Mejor val_loss: 0.002215. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.002144. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.002035. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.001886. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.001835. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 11.1s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0030 | Val MAE: 0.05 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 10.8s
✅ Mejor val_loss: 0.001682. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 10.9s
✅ Mejor val_loss: 0.001631. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 10.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 11.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 10.9s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 19 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0019

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 64
   - num_layers: 2
   - lr: 0.007260993651090153


📍 Parking 77 | 🧠 Modelo: GRU
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0140 | Train MAE: 0.09 | Val Loss: 0.0051 | Val MAE: 0.05 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.005055. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0031 | Val MAE: 0.04 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.003135. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 4.8s
✅ Mejor val_loss: 0.002063. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 4.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.

🧪 Optimizando GRU con Optuna para parking 77...


🔁 Trial 0
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00703
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0100 | Train MAE: 0.07 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.002826. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0040 | Train MAE: 0.05 | Val Loss: 0.0043 | Val MAE: 0.05 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0036 | Train MAE: 0.05 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.6s
✅ Mejor val_loss: 0.002370. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.002306. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.001989. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.001855. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.001795. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.001588. Guardando modelo...

📊 Epoch 15/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 19 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0016

🔁 Trial 1
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00715
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0513 | Train MAE: 0.17 | Val Loss: 0.0075 | Val MAE: 0.06 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.007520. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0068 | Train MAE: 0.06 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002736. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0044 | Train MAE: 0.05 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002621. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0037 | Train MAE: 0.05 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002450. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0034 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002271. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0032 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.002225. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001801. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001718. Guardando modelo...

📊 Epoch 16/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 20 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0019

🔁 Trial 2
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00962
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0106 | Train MAE: 0.07 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002420. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002289. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001905. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001881. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001544. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0017

🔁 Trial 3
   🔧 Params → hidden_size: 32, num_layers: 4, lr: 0.00591
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0110 | Train MAE: 0.07 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.002154. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.002091. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 5.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.001834. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0034 | Val MAE: 0.05 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.001527. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.001458. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0021 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0017

🔁 Trial 4
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00572
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0084 | Train MAE: 0.06 | Val Loss: 0.0026 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002641. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002350. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.002248. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0029 | Val MAE: 0.05 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001866. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001696. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.001595. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.001557. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0033 | Val MAE: 0.05 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0021

🔁 Trial 5
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00870
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0078 | Train MAE: 0.06 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001942. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001760. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.001678. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001578. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 13 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0017

🔁 Trial 6
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00985
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0483 | Train MAE: 0.18 | Val Loss: 0.0332 | Val MAE: 0.16 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.033176. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0228 | Train MAE: 0.12 | Val Loss: 0.0280 | Val MAE: 0.14 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.027969. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0224 | Train MAE: 0.12 | Val Loss: 0.0276 | Val MAE: 0.13 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.027583. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0221 | Train MAE: 0.11 | Val Loss: 0.0282 | Val MAE: 0.14 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0218 | Train MAE: 0.11 | Val Loss: 0.0286 | Val MAE: 0.13 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0221 | Train MAE: 0.11 | Val Loss: 0.0273 | Val MAE: 0.13 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.027270. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0219 | Train MAE: 0.11 | Val Loss: 0.0274 | Val MAE: 0.13 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0182 | Train MAE: 0.10 | Val Loss: 0.0038 | Val MAE: 0.05 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.003793. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0039 | Train MAE: 0.05 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.001809. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001782. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0033 | Val MAE: 0.05 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0022

🔁 Trial 7
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00864
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0097 | Train MAE: 0.07 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002153. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001964. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001944. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001733. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 12 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0019

🔁 Trial 8
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00608
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0082 | Train MAE: 0.07 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002299. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0033 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002115. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002067. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001833. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001815. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001768. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001720. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001665. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001608. Guardando modelo...

📊 Epoch 19/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001476. Guardando modelo...

📊 Epoch 24/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 26/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 27/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 28/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 28 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0016

🔁 Trial 9
   🔧 Params → hidden_size: 16, num_layers: 3, lr: 0.00519
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0115 | Train MAE: 0.08 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002492. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.002061. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001912. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
✅ Mejor val_loss: 0.001872. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.001860. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.3s
✅ Mejor val_loss: 0.001703. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0025 | Val MAE: 0.04 | ⏱️ Time: 5.3s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.2s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0018

🔁 Trial 10
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00711
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0106 | Train MAE: 0.07 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.002093. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.001633. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.6s
✅ Mejor val_loss: 0.001611. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0028 | Val MAE: 0.04 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.001586. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.001563. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.001534. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.001504. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.4s
✅ Mejor val_loss: 0.001472. Guardando modelo...

📊 Epoch 18/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 21/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 5.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 22 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0015

🔁 Trial 11
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00716
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0107 | Train MAE: 0.07 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.001985. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.001948. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0021 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.001831. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0022 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.5s
✅ Mejor val_loss: 0.001682. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 5.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 11 por falta de mejora.
🎯 Resultado trial 11 → val_loss = 0.0018

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 64
   - num_layers: 4
   - lr: 0.007111697708859464


📍 Parking 78 | 🧠 Modelo: GRU
──────────────────────────────
🛠️ Entrenamiento versión VANILLA

📊 Epoch 1/30 | Train Loss: 0.0491 | Train MAE: 0.14 | Val Loss: 0.0115 | Val MAE: 0.08 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.011482. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0092 | Train MAE: 0.06 | Val Loss: 0.0072 | Val MAE: 0.06 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.007184. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0061 | Train MAE: 0.05 | Val Loss: 0.0052 | Val MAE: 0.05 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.005185. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0043 | Train MAE: 0.04 | Val Loss: 0.0042 | Val MAE: 0.04 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0030 | Train MAE: 0.03 | Val Loss: 0.0028 | Val MAE: 0.03 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.002764. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0025 | Train MAE: 0.03 | Val Loss: 0.0025 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.

🧪 Optimizando GRU con Optuna para parking 78...


🔁 Trial 0
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00824
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0115 | Train MAE: 0.07 | Val Loss: 0.0019 | Val MAE: 0.02 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001869. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 3/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001424. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001367. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001329. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001267. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.001122. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0011 | Train MAE: 0.02 | Val Loss: 0.0018 | Val MAE: 0.04 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 0 → val_loss = 0.0018

🔁 Trial 1
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00992
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0298 | Train MAE: 0.13 | Val Loss: 0.0144 | Val MAE: 0.07 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.014407. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0053 | Train MAE: 0.05 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.002129. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0026 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.002116. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001791. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001602. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 4.0s
✅ Mejor val_loss: 0.001534. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001460. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001351. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 18 por falta de mejora.
🎯 Resultado trial 1 → val_loss = 0.0018

🔁 Trial 2
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00898
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0216 | Train MAE: 0.08 | Val Loss: 0.0027 | Val MAE: 0.03 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.002668. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0025 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001758. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001366. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0023 | Val MAE: 0.04 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 8 por falta de mejora.
🎯 Resultado trial 2 → val_loss = 0.0016

🔁 Trial 3
   🔧 Params → hidden_size: 32, num_layers: 2, lr: 0.00528
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0359 | Train MAE: 0.11 | Val Loss: 0.0041 | Val MAE: 0.04 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.004132. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0044 | Train MAE: 0.05 | Val Loss: 0.0022 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.002242. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0027 | Val MAE: 0.05 | ⏱️ Time: 3.4s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0023 | Train MAE: 0.03 | Val Loss: 0.0019 | Val MAE: 0.03 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001892. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001621. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001311. Guardando modelo...

📊 Epoch 8/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001263. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001225. Guardando modelo...

📊 Epoch 13/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 17/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 17 por falta de mejora.
🎯 Resultado trial 3 → val_loss = 0.0013

🔁 Trial 4
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00565
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0391 | Train MAE: 0.15 | Val Loss: 0.0280 | Val MAE: 0.13 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.028047. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0245 | Train MAE: 0.12 | Val Loss: 0.0198 | Val MAE: 0.09 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.019825. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0162 | Train MAE: 0.08 | Val Loss: 0.0179 | Val MAE: 0.08 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.017892. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0159 | Train MAE: 0.08 | Val Loss: 0.0172 | Val MAE: 0.08 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.017219. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0155 | Train MAE: 0.08 | Val Loss: 0.0175 | Val MAE: 0.09 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0154 | Train MAE: 0.08 | Val Loss: 0.0173 | Val MAE: 0.08 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0155 | Train MAE: 0.08 | Val Loss: 0.0173 | Val MAE: 0.08 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0153 | Train MAE: 0.08 | Val Loss: 0.0176 | Val MAE: 0.08 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0152 | Train MAE: 0.08 | Val Loss: 0.0174 | Val MAE: 0.08 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 9 por falta de mejora.
🎯 Resultado trial 4 → val_loss = 0.0174

🔁 Trial 5
   🔧 Params → hidden_size: 64, num_layers: 3, lr: 0.00803
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0127 | Train MAE: 0.07 | Val Loss: 0.0049 | Val MAE: 0.06 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.004856. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0024 | Train MAE: 0.04 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001465. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001355. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001278. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0013 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.001229. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.04 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 15 por falta de mejora.
🎯 Resultado trial 5 → val_loss = 0.0013

🔁 Trial 6
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00650
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0119 | Train MAE: 0.07 | Val Loss: 0.0030 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.003042. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0027 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001731. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001532. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001510. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001336. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001293. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001187. Guardando modelo...

📊 Epoch 10/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 14 por falta de mejora.
🎯 Resultado trial 6 → val_loss = 0.0012

🔁 Trial 7
   🔧 Params → hidden_size: 32, num_layers: 3, lr: 0.00676
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0307 | Train MAE: 0.12 | Val Loss: 0.0193 | Val MAE: 0.08 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.019338. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0161 | Train MAE: 0.08 | Val Loss: 0.0170 | Val MAE: 0.09 | ⏱️ Time: 3.6s
✅ Mejor val_loss: 0.016961. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0157 | Train MAE: 0.08 | Val Loss: 0.0175 | Val MAE: 0.08 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 4/30 | Train Loss: 0.0155 | Train MAE: 0.08 | Val Loss: 0.0177 | Val MAE: 0.08 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0153 | Train MAE: 0.08 | Val Loss: 0.0190 | Val MAE: 0.08 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0155 | Train MAE: 0.08 | Val Loss: 0.0179 | Val MAE: 0.08 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0152 | Train MAE: 0.08 | Val Loss: 0.0188 | Val MAE: 0.08 | ⏱️ Time: 3.6s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 7 por falta de mejora.
🎯 Resultado trial 7 → val_loss = 0.0188

🔁 Trial 8
   🔧 Params → hidden_size: 64, num_layers: 4, lr: 0.00785
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0269 | Train MAE: 0.11 | Val Loss: 0.0046 | Val MAE: 0.04 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.004606. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0041 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001736. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001592. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0027 | Val MAE: 0.04 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001320. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 10 por falta de mejora.
🎯 Resultado trial 8 → val_loss = 0.0014

🔁 Trial 9
   🔧 Params → hidden_size: 16, num_layers: 4, lr: 0.00716
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0227 | Train MAE: 0.11 | Val Loss: 0.0031 | Val MAE: 0.03 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.003135. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0039 | Train MAE: 0.04 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.7s
✅ Mejor val_loss: 0.002009. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0029 | Train MAE: 0.04 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001665. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0028 | Train MAE: 0.04 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 5/30 | Train Loss: 0.0026 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 6/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001572. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0021 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 9/30 | Train Loss: 0.0025 | Train MAE: 0.03 | Val Loss: 0.0020 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.8s
✅ Mejor val_loss: 0.001426. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 4.0s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.8s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 9 → val_loss = 0.0016

🔁 Trial 10
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00618
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0145 | Train MAE: 0.08 | Val Loss: 0.0030 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.003050. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0030 | Train MAE: 0.04 | Val Loss: 0.0022 | Val MAE: 0.04 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.002185. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0025 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001774. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001725. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0022 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001667. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001582. Guardando modelo...

📊 Epoch 7/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0018 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001536. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001486. Guardando modelo...

📊 Epoch 11/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001350. Guardando modelo...

📊 Epoch 12/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0016 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 5/5 sin mejora
⛔ Parada temprana en epoch 16 por falta de mejora.
🎯 Resultado trial 10 → val_loss = 0.0014

🔁 Trial 11
   🔧 Params → hidden_size: 16, num_layers: 2, lr: 0.00689
────────────────────────────────────────────────────────────

📊 Epoch 1/30 | Train Loss: 0.0319 | Train MAE: 0.12 | Val Loss: 0.0076 | Val MAE: 0.07 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.007630. Guardando modelo...

📊 Epoch 2/30 | Train Loss: 0.0057 | Train MAE: 0.05 | Val Loss: 0.0026 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.002581. Guardando modelo...

📊 Epoch 3/30 | Train Loss: 0.0031 | Train MAE: 0.04 | Val Loss: 0.0021 | Val MAE: 0.04 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.002082. Guardando modelo...

📊 Epoch 4/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.02 | ⏱️ Time: 3.4s
✅ Mejor val_loss: 0.001716. Guardando modelo...

📊 Epoch 5/30 | Train Loss: 0.0024 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001608. Guardando modelo...

📊 Epoch 6/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 7/30 | Train Loss: 0.0021 | Train MAE: 0.03 | Val Loss: 0.0024 | Val MAE: 0.04 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 8/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001480. Guardando modelo...

📊 Epoch 9/30 | Train Loss: 0.0020 | Train MAE: 0.03 | Val Loss: 0.0016 | Val MAE: 0.02 | ⏱️ Time: 3.7s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 10/30 | Train Loss: 0.0019 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 11/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 12/30 | Train Loss: 0.0018 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 13/30 | Train Loss: 0.0017 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001334. Guardando modelo...

📊 Epoch 14/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0015 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 15/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0017 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 16/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001234. Guardando modelo...

📊 Epoch 17/30 | Train Loss: 0.0015 | Train MAE: 0.03 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 18/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 19/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0014 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 20/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001184. Guardando modelo...

📊 Epoch 21/30 | Train Loss: 0.0014 | Train MAE: 0.03 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 22/30 | Train Loss: 0.0014 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 23/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 24/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 4/5 sin mejora

📊 Epoch 25/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001170. Guardando modelo...

📊 Epoch 26/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 3.5s
✅ Mejor val_loss: 0.001079. Guardando modelo...

📊 Epoch 27/30 | Train Loss: 0.0013 | Train MAE: 0.02 | Val Loss: 0.0012 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 1/5 sin mejora

📊 Epoch 28/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 2/5 sin mejora

📊 Epoch 29/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0013 | Val MAE: 0.03 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 3/5 sin mejora

📊 Epoch 30/30 | Train Loss: 0.0012 | Train MAE: 0.02 | Val Loss: 0.0011 | Val MAE: 0.02 | ⏱️ Time: 3.5s
🛑 EarlyStopping: 4/5 sin mejora
🎯 Resultado trial 11 → val_loss = 0.0011

🥇 Mejores hiperparámetros encontrados:
   - hidden_size: 16
   - num_layers: 2
   - lr: 0.006894023509610913

## 16. Predicciones sobre el conjunto de test

In [39]:
def predict_and_evaluate(model, dataloader, metrics, device="cpu", parking_id=None,
                         modelo=None, tipo=None, base_dir="../test_predictions"):
    """
    Predice sobre el dataloader, calcula métricas y guarda resultados en carpeta estructurada por parking.

    Args:
        model (nn.Module): Modelo entrenado.
        dataloader (DataLoader): Conjunto de test.
        metrics (torchmetrics.MetricCollection): Métricas para calcular.
        device (str): "cpu" o "cuda".
        parking_id (int or str): ID del parking (para crear carpeta).
        modelo (str): Nombre del modelo ("lstm", "rnn", etc.).
        tipo (str): Tipo de experimento ("vanilla", "optuna", etc.).
        base_dir (str): Carpeta base para guardar.

    Returns:
        dict: Métricas de test.
        pd.DataFrame: DataFrame con y_true y y_pred.
    """
    model.eval()
    model.to(device)
    metrics.to(device)
    metrics.reset()

    all_preds = []
    all_targets = []

    with torch.no_grad():
        for x_batch, y_batch in dataloader:
            x_batch = x_batch.to(device)
            y_batch = y_batch.to(device)

            y_pred = model(x_batch)

            all_preds.append(y_pred.cpu())
            all_targets.append(y_batch.cpu())

    # Unir predicciones y targets
    y_pred = torch.cat(all_preds, dim=0).squeeze().numpy()
    y_true = torch.cat(all_targets, dim=0).squeeze().numpy()

    # Calcular métricas
    y_pred_tensor = torch.tensor(y_pred)
    y_true_tensor = torch.tensor(y_true)
    metrics.reset()
    metrics.update(y_pred_tensor, y_true_tensor)
    results = {k: v.item() for k, v in metrics.compute().items()}

    # Guardar resultados
    base_path = get_experiment_path(base_dir, parking_id, modelo, tipo)
    test_path = os.path.join(base_path, "test")
    os.makedirs(test_path, exist_ok=True)

    df = pd.DataFrame({
        "y_true": y_true,
        "y_pred": y_pred
    })
    df.to_csv(os.path.join(test_path, "predictions.csv"), index=False)

    with open(os.path.join(test_path, "test_metrics.json"), "w") as f:
        json.dump(results, f, indent=2)

    return results, df

In [40]:
for modelo in ["lstm", "rnn", "gru"]:
    model_class = model_classes[modelo]
    
    for pid in test_dataloaders.keys():
        for tipo in ["vanilla", "optuna"]:
            print(f"📊 Parking {pid} | Modelo {modelo.upper()} | Versión: {tipo}")

            # Ruta base
            exp_path = get_experiment_path("../experiments/validation", parking_id=pid, modelo=modelo, tipo=tipo)
            model_path = os.path.join(exp_path, "best_model.pt")

            if not os.path.exists(model_path):
                print(f"⚠️ No se encontró el modelo en {model_path}. Saltando...\n")
                continue

            # Obtener hiperparámetros si es versión optuna
            if tipo == "optuna":
                params_path = os.path.join(exp_path, "best_params.json")
                if not os.path.exists(params_path):
                    print(f"⚠️ No se encontraron parámetros óptimos en {params_path}. Saltando...\n")
                    continue
                with open(params_path, "r") as f:
                    best_params = json.load(f)

                model = model_class(
                    input_size=INPUT_SIZE,
                    hidden_size=best_params["hidden_size"],
                    output_size=OUTPUT_SIZE,
                    num_layers=best_params["num_layers"]
                )

            else:  # Versión vanilla
                model = model_class(
                    input_size=INPUT_SIZE,
                    hidden_size=HIDDEN_SIZE,
                    output_size=OUTPUT_SIZE,
                    num_layers=NUM_LAYERS
                )

            # Cargar pesos
            model.load_state_dict(torch.load(model_path, map_location=DEVICE))
            
            # Ejecutar predicción
            test_results, test_df = predict_and_evaluate(
                model=model,
                dataloader=test_dataloaders[pid],
                metrics=metrics.clone(),
                device=DEVICE,
                parking_id=pid,
                modelo=modelo,
                tipo=tipo,
                base_dir="../test_predictions"
            )

            print(f"✅ Test completado. MAE: {test_results['MAE']:.2f}, RMSE: {test_results['RMSE']:.2f}\n")

📊 Parking 6 | Modelo LSTM | Versión: vanilla
✅ Test completado. MAE: 0.03, RMSE: 0.05

📊 Parking 6 | Modelo LSTM | Versión: optuna
✅ Test completado. MAE: 0.03, RMSE: 0.05

📊 Parking 7 | Modelo LSTM | Versión: vanilla
✅ Test completado. MAE: 0.03, RMSE: 0.04

📊 Parking 7 | Modelo LSTM | Versión: optuna
✅ Test completado. MAE: 0.03, RMSE: 0.04

📊 Parking 8 | Modelo LSTM | Versión: vanilla
✅ Test completado. MAE: 0.02, RMSE: 0.03

📊 Parking 8 | Modelo LSTM | Versión: optuna
✅ Test completado. MAE: 0.02, RMSE: 0.03

📊 Parking 13 | Modelo LSTM | Versión: vanilla
✅ Test completado. MAE: 0.02, RMSE: 0.03

📊 Parking 13 | Modelo LSTM | Versión: optuna
✅ Test completado. MAE: 0.02, RMSE: 0.03

📊 Parking 34 | Modelo LSTM | Versión: vanilla
✅ Test completado. MAE: 0.04, RMSE: 0.05

📊 Parking 34 | Modelo LSTM | Versión: optuna
✅ Test completado. MAE: 0.07, RMSE: 0.09

📊 Parking 75 | Modelo LSTM | Versión: vanilla
✅ Test completado. MAE: 0.04, RMSE: 0.05

📊 Parking 75 | Modelo LSTM | Versión: optuna
✅ Test completado. MAE: 0.03, RMSE: 0.04

📊 Parking 77 | Modelo LSTM | Versión: vanilla
✅ Test completado. MAE: 0.03, RMSE: 0.05

📊 Parking 77 | Modelo LSTM | Versión: optuna
✅ Test completado. MAE: 0.03, RMSE: 0.04

📊 Parking 78 | Modelo LSTM | Versión: vanilla
✅ Test completado. MAE: 0.03, RMSE: 0.05

📊 Parking 78 | Modelo LSTM | Versión: optuna
✅ Test completado. MAE: 0.02, RMSE: 0.04

📊 Parking 6 | Modelo RNN | Versión: vanilla
✅ Test completado. MAE: 0.03, RMSE: 0.05

📊 Parking 6 | Modelo RNN | Versión: optuna
✅ Test completado. MAE: 0.04, RMSE: 0.05

📊 Parking 7 | Modelo RNN | Versión: vanilla
✅ Test completado. MAE: 0.03, RMSE: 0.04

📊 Parking 7 | Modelo RNN | Versión: optuna
✅ Test completado. MAE: 0.03, RMSE: 0.04

📊 Parking 8 | Modelo RNN | Versión: vanilla
✅ Test completado. MAE: 0.03, RMSE: 0.04

📊 Parking 8 | Modelo RNN | Versión: optuna
✅ Test completado. MAE: 0.03, RMSE: 0.04

📊 Parking 13 | Modelo RNN | Versión: vanilla
✅ Test completado. MAE: 0.02, RMSE: 0.04

📊 Parking 13 | Modelo RNN | Versión: optuna
✅ Test completado. MAE: 0.02, RMSE: 0.03

📊 Parking 34 | Modelo RNN | Versión: vanilla
✅ Test completado. MAE: 0.03, RMSE: 0.05

📊 Parking 34 | Modelo RNN | Versión: optuna
✅ Test completado. MAE: 0.05, RMSE: 0.06

📊 Parking 75 | Modelo RNN | Versión: vanilla
✅ Test completado. MAE: 0.04, RMSE: 0.05

📊 Parking 75 | Modelo RNN | Versión: optuna
✅ Test completado. MAE: 0.03, RMSE: 0.05

📊 Parking 77 | Modelo RNN | Versión: vanilla
✅ Test completado. MAE: 0.04, RMSE: 0.05

📊 Parking 77 | Modelo RNN | Versión: optuna
✅ Test completado. MAE: 0.04, RMSE: 0.05

📊 Parking 78 | Modelo RNN | Versión: vanilla
✅ Test completado. MAE: 0.03, RMSE: 0.05

📊 Parking 78 | Modelo RNN | Versión: optuna
✅ Test completado. MAE: 0.02, RMSE: 0.04

📊 Parking 6 | Modelo GRU | Versión: vanilla
✅ Test completado. MAE: 0.03, RMSE: 0.05

📊 Parking 6 | Modelo GRU | Versión: optuna
✅ Test completado. MAE: 0.03, RMSE: 0.05

📊 Parking 7 | Modelo GRU | Versión: vanilla
✅ Test completado. MAE: 0.03, RMSE: 0.04

📊 Parking 7 | Modelo GRU | Versión: optuna
✅ Test completado. MAE: 0.03, RMSE: 0.04

📊 Parking 8 | Modelo GRU | Versión: vanilla
✅ Test completado. MAE: 0.02, RMSE: 0.03

📊 Parking 8 | Modelo GRU | Versión: optuna
✅ Test completado. MAE: 0.02, RMSE: 0.03

📊 Parking 13 | Modelo GRU | Versión: vanilla
✅ Test completado. MAE: 0.02, RMSE: 0.03

📊 Parking 13 | Modelo GRU | Versión: optuna
✅ Test completado. MAE: 0.02, RMSE: 0.03

📊 Parking 34 | Modelo GRU | Versión: vanilla
✅ Test completado. MAE: 0.04, RMSE: 0.05

📊 Parking 34 | Modelo GRU | Versión: optuna
✅ Test completado. MAE: 0.05, RMSE: 0.06

📊 Parking 75 | Modelo GRU | Versión: vanilla
✅ Test completado. MAE: 0.03, RMSE: 0.05

📊 Parking 75 | Modelo GRU | Versión: optuna
✅ Test completado. MAE: 0.03, RMSE: 0.04

📊 Parking 77 | Modelo GRU | Versión: vanilla
✅ Test completado. MAE: 0.03, RMSE: 0.05

📊 Parking 77 | Modelo GRU | Versión: optuna
✅ Test completado. MAE: 0.03, RMSE: 0.04

📊 Parking 78 | Modelo GRU | Versión: vanilla
✅ Test completado. MAE: 0.03, RMSE: 0.05

📊 Parking 78 | Modelo GRU | Versión: optuna
✅ Test completado. MAE: 0.02, RMSE: 0.04